Alfresco/alfresco-community-repo

- repository/src/main/java/org/alfresco/repo/deployment/DeploymentMethod.java
- repository/src/main/resources/alfresco/repository.properties
Added ANSIBLE as an option for deployment method
> OPSEXP-492: Add ANSIBLE deployment method

- remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
(cherry picked from commit 73b393a54157fb9fec857d9a27b3640933530033)
> MNT-22061: REST api does not update the primary path on new version upload

- repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
- repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
- repository/src/main/java/org/alfresco/repo/rendition2/TransformDefinition.java
- repository/src/main/java/org/alfresco/repo/rendition2/TransformRequestProcessor.java
- repository/src/main/resources/alfresco/content-services-context.xml
- repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java
Found the code that makes ATS extract metadata on the branch that removes legacy transforms.
> ACS-938 metadata is not added when using Transform Service

- remote-api/src/main/java/org/alfresco/repo/web/scripts/replication/AbstractReplicationWebscript.java
Added check for String instanceof. The implementation of the method getString() was changed for library org.json.
> Added check for properties of jsonObject scheduler.start.

- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/archive/archivednode.put.desc.xml
- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/archive/archivednodes.delete.desc.xml
- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/archive/archivednodes.get.desc.xml
Fixed the issue by using System user instead of the admin user
> APPS-688: Fixed the issue by using System user instead of the admin user

- repository/src/main/java/org/alfresco/repo/domain/node/NodePropertyValue.java
This PR contains changes required to integrate the accelerated query population. The main of the code is in the enterprise repo, see the PR there at https://github.com/Alfresco/alfresco-enterprise-repo/pull/147
> Added new method to convert system type to ordinal

- repository/src/main/java/org/alfresco/repo/activities/feed/FeedTaskProcessor.java
Decrease log severity to reduce pollution in Log when a site get deleted
> Decrease log severity

- pom.xml
- repository/src/main/java/org/alfresco/messaging/camel/configuration/ConnectionFactoryConfiguration.java
- repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging-context.xml
- upgrade Gytheio
- move jms bean to messaging-context.xml
> ACS-1170 : Release Gytheio 0.12 - ACS 7.0 compatible

- repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
- repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
Fix to handle an unchecked NPE occurring as described in ACS-1160.
> [ACS-1160] Handle null Authority

- remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/lookups/PersonPropertyLookup.java
- remote-api/src/main/resources/alfresco/public-rest-context.xml
- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Copy of https://github.com/Alfresco/alfresco-remote-api/pull/866
> Fix MNT-21991 customizable personLookupProperties for REST API

- remote-api/src/main/java/org/alfresco/rest/api/model/AbstractClass.java
- remote-api/src/main/java/org/alfresco/rest/api/model/Aspect.java
- remote-api/src/main/java/org/alfresco/rest/api/model/Model.java
- remote-api/src/main/java/org/alfresco/rest/api/model/Type.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/BaseModelApiTest.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/TestAspects.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/TestTypes.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Aspect.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Type.java
depends https://github.com/Alfresco/rest-api-explorer/pull/124
> [REPO-5440] show model in the aspect/type api

- core/src/main/java/org/alfresco/util/TempFileProvider.java
- repository/src/main/resources/alfresco/repository.properties
- repository/src/main/resources/alfresco/scheduled-jobs-context.xml
- added nr of files and time limits
> REPO-5571 : Change the tempFileCleanerTrigger to work at scale

- pom.xml
Updated webscripts version from 8.15 to 8.17
> fix/APPS-update-webscripts-version to 8.17

- core/src/main/java/org/alfresco/util/TempFileProvider.java
> REPO-5571 : Add tempFileCleanerTrigger configurations to be able to limit the job duration/quantity

- remote-api/src/main/java/org/alfresco/rest/api/impl/AspectsImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/TypesImpl.java
https://alfresco.atlassian.net/browse/REPO-5596
> [REPO-5552] Fix get Aspect/Type api random error

- scripts/travis/build_functions.sh
- mirror the `build_functions.sh` script from the other ACS repos
- no practical functional change
> Update the ACS build scripts

- packaging/war/src/main/resources/alfresco/web-client-security-config.xml
- packaging/war/src/main/webapp/WEB-INF/web.xml
Added X-Frame-Options security header for admin console.
https://alfresco.atlassian.net/browse/MNT-22184
> MNT-22184 Add security header for admin console

- repository/src/main/resources/alfresco/repository.properties
- repository/src/main/resources/alfresco/scheduled-jobs-context.xml
This would allow to update the cron expression, especially to put a year 2099 on read-only/Solr tracking repositories
> Externalize the nodeServiceCleanup CRON expression

- repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
- repository/src/main/java/org/alfresco/repo/domain/schema/script/ScriptExecutorImpl.java
- repository/src/test/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutorTest.java
Reverts Alfresco/alfresco-community-repo#390
> Revert "MNT-22186: propTablesCleanupJobDetail v2 can cause Out of Memory erro…"

- pom.xml
- upgrade Trashcan Cleaner module to 2.4
> ACS-1404 : Trashcan Cleaner job doesn't work when trying to delete from a big amount of data

- repository/src/main/resources/alfresco/core-services-context.xml
- fix previous blatant typo (thanks Stefan)
- https://github.com/Alfresco/alfresco-community-repo/pull/427
> ATS-892 / ATS-909: Add IPTC model

- repository/src/test/java/org/alfresco/util/schemacomp/SchemaBootstrapTest.java
Now automating the update of the test schema reference file so that it is not required to be done manually whenever the main one is updated.
> REPO-5624 Reimplement SchemaBootstrapTest

- .travis.yml
* Now only run on master and release branches by default.
> Turn off db jobs on pull requests

- repository/src/main/java/org/alfresco/repo/rendition2/TransformationOptionsConverter.java
- repository/src/test/java/org/alfresco/repo/rendition2/TransformationOptionsConverterTest.java
Turns out we can put these changes on master (7.1.0) and 7.0.N (7.0.1) after all.
> MNT-21694 transform option converter

- packaging/war/src/main/webapp/error.jsp
- packaging/war/src/main/webapp/index.jsp
* [MNT-22183] Use absolut paths for stylesheets
[MNT-22183]: https://alfresco.atlassian.net/browse/MNT-22183
> [MNT-22183] Use absolute paths for stylesheets (#383)

- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/site/site-admin-sites.get.json.ftl
- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/site/site.lib.ftl
- Fixed some sites FTLs that failed due to site description being null
> SHA-2478 : Some Share features stop working if a site has description = null

- repository/src/main/java/org/alfresco/repo/domain/schema/SchemaBootstrap.java
Now only considering instances of a Difference.
> ACS-1587 Postsql DB Test Schema Differences Are Reported Fails

- repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
- repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
- commit changes to db anytime `deleteBatchSize` of deleted data is reached
> ACS-1600 : Error when running propTablesCleanupJob on an env with 100million records in alf_prop_value

- repository/src/main/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStore.java
- repository/src/test/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStoreTest.java
> ACS-1603 : Update & tests for AbstractTenantRoutingContentStore

- repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
- repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessor.java
- repository/src/main/resources/alfresco/repository.properties
- repository/src/main/resources/alfresco/subsystems/Search/common-search-context.xml
- repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
Changes made to correct the value of totalItems when performing a TMDQ.
View also companion PR on the enterprise project here https://github.com/Alfresco/alfresco-enterprise-repo/pull/422
> MNT-22385 Cmis query GetTotalNumItems is returning wrong value

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/disposition/DispositionServiceImpl.java
- amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/integration/disposition/DispositionScheduleInheritanceTest.java
- amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/util/CommonRMTestUtils.java
Changes  for RM-7103 from https://github.com/Alfresco/governance-services/pull/1421
> Feature/rm 7103 changes from governance pr#1421

- pom.xml
Reverts Alfresco/alfresco-community-repo#451
> Revert "Bump mariadb-java-client from 2.7.2 to 2.7.3"

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/repo/rule/ExtendedRuleServiceImpl.java
APPS-491
[AGS] Value saved for Retention Parameter is different than the one introduced in UI
> APPS-491 - [AGS] Value saved for Retention Parameter is different

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuter.java
- amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuterUnitTest.java
batchSize will default to 500 if the given value is smaller than 1
added unit test.
Cherry picked fix from AGS project
> RM-7169 : Disposition Lifecycle job runs in a infinite loop

- repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Original PR: #391 
(cherry picked from commit a8959b98c1e90fca83a55e427ab5d84a47f4a93b)
> [MNT-21611] Removed HTML transformation pipelines (with LibreOffice). Added new HTML pipelines via TEXT.

- remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- repository/src/main/resources/alfresco/public-services-security-context.xml
- added update
Author: @tzclucian
> ACS-1633 : Storage classes - REST api - PUT /nodes/{nodeId}

- remote-api/src/main/java/org/alfresco/rest/api/People.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/PeopleImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/people/PeopleEntityResource.java
- repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordService.java
- repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
- repository/src/main/java/org/alfresco/repo/security/authentication/activiti/AbstractResetPasswordDelegate.java
- repository/src/main/java/org/alfresco/repo/security/authentication/activiti/PerformResetPasswordDelegate.java
- repository/src/main/java/org/alfresco/repo/security/authentication/activiti/SendResetPasswordConfirmationEmailDelegate.java
- repository/src/main/java/org/alfresco/repo/security/authentication/activiti/SendResetPasswordEmailDelegate.java
- repository/src/main/java/org/alfresco/repo/workflow/WorkflowModelResetPassword.java
Deprecate code used for reset-password and request-password-reset APIs
> [ACS-1715] Deprecate reset-password APIs

- repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
> ACS-1734 Remove libreofficeToPdf + libreofficeToPdfBoxViaPdf

- repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
> ACS-1734 Remove libreofficeToPdf + libreofficeToPdfBoxViaPdf 

- repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
- repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
- repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
(cherry picked from commit ac4a1643e1bd55565288a6c7ffefd232607c46f7)
> PRODSEC-4422 ScriptActionExecuter fix

- repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
- repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
- repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
(cherry picked from commit ac4a1643e1bd55565288a6c7ffefd232607c46f7)
> PRODSEC-4422 - ScriptActionExecuter fix

- repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
- repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
- repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
(cherry picked from commit ac4a1643e1bd55565288a6c7ffefd232607c46f7)
> PRODSEC-4422 - ScriptActionExecuter

- repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
- repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
- repository/src/main/java/org/alfresco/repo/domain/schema/script/ScriptExecutorImpl.java
- repository/src/test/java/org/alfresco/AllDBTestsTestSuite.java
- repository/src/test/java/org/alfresco/AppContextExtraTestSuite.java
- repository/src/test/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutorTest.java
Cherry-picked f201f35 7a02081 from master to release/7.0.N
Cherry-picked 3f52aec from release/7.0.N to release/6.2.N
(cherry picked from commit b880bf4e1b778b2f30cd0d082179ebb5dc9976c8)
> MNT-22512: propTablesCleanupJobDetail v2 can cause Out of Memory

- remote-api/src/main/java/org/alfresco/rest/api/impl/directurl/RestApiDirectUrlConfig.java
- remote-api/src/test/java/org/alfresco/AppContext04TestSuite.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/RestApiDirectUrlConfigUnitTest.java
- repository/src/main/java/org/alfresco/repo/content/directurl/AbstractDirectUrlConfig.java
- repository/src/main/java/org/alfresco/repo/content/directurl/ContentStoreDirectUrlConfig.java
- repository/src/main/java/org/alfresco/repo/content/directurl/DirectUrlConfig.java
- repository/src/main/java/org/alfresco/repo/content/directurl/InvalidDirectAccessUrlConfigException.java
- repository/src/main/java/org/alfresco/repo/content/directurl/SystemWideDirectUrlConfig.java
- repository/src/main/resources/alfresco/content-services-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
- repository/src/test/java/org/alfresco/repo/content/directurl/ContentStoreDirectUrlConfigUnitTest.java
- repository/src/test/java/org/alfresco/repo/content/directurl/SystemWideDirectUrlConfigUnitTest.java
The set up and validation of the 3 properties configurations for direct access URLs.
> Acs 1865 impl configs for da us

- remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
-add test for RequestContentDirectUrl
> ACS-1830 - Test requestContentDirectUrl for Nodes REST API endpoint

- data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
- data-model/src/main/java/org/alfresco/service/cmr/repository/DirectAccessUrl.java
- repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
- repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
- repository/src/main/java/org/alfresco/repo/content/directurl/DirectAccessUrlDisabledException.java
- repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
- repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
- repository/src/main/resources/alfresco/content-services-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
- repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
- repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
- repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
- repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
This includes the work for both [ACS-1781](https://alfresco.atlassian.net/browse/ACS-1781) and [ACS-1782](https://alfresco.atlassian.net/browse/ACS-1782)
> Feature/acs 1782 impl request DAU in content service

- amps/ags/rm-community/rm-community-repo/docker-compose.yml
use base image according to the changes added within PR #619 https://github.com/Alfresco/alfresco-community-repo/pull/619
> APPS-1068 Update the docker-compose

- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
- add test for request DAU for versions
> ACS-1832 - Test requestContentDirectUrl for Versions REST API endpoint

- remote-api/src/test/java/org/alfresco/rest/api/tests/GroupsTest.java
- repository/src/main/java/org/alfresco/repo/security/authority/AuthorityServiceImpl.java
- repository/src/main/java/org/alfresco/service/cmr/security/AuthorityService.java
- repository/src/main/resources/alfresco/bootstrap/alfrescoAuthorityStore.xml
- repository/src/main/resources/alfresco/bootstrap/alfrescoAuthorityStoreDefaultMembers.xml
- repository/src/main/resources/alfresco/public-services-security-context.xml
- repository/src/test/java/org/alfresco/repo/security/authority/AuthorityServiceTest.java
PRODMAN-493/REPO-5659: Added **ALFRESCO_SYSTEM_ADMINISTRATORS** group authority.
> REPO-5659: Added ALFRESCO_SYSTEM_ADMINISTRATORS group authority.

- repository/src/main/resources/alfresco/messages/patch-service.properties
- repository/src/main/resources/alfresco/patch/patch-services-context.xml
- repository/src/main/resources/alfresco/repository.properties
A patch for the new added ALFRESCO_SYSTEM_ADMINISTRATORS group.
> REPO-5660: A patch for the ALFRESCO_SYSTEM_ADMINISTRATORS group

- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
- add rendition requestContentDirectUrl test
> ACS-1831 - Test requestContentDirectUrl for Renditions REST API endpoint

- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
-add requestContentDirectUrl test for versions renditions
> ACS-1833 - Test requestContentDirectUrl for Versions Renditions

- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/record/RecordProperties.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/recordcategory/RecordCategoryChildProperties.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/recordcategories/MoveRecCategoriesWithRSTests.java
End to end tests for APPS-1004 and APPS-1005
> end to end tests for APPS-1004 and APPS-1005

- pom.xml
(cherry picked from commit 411f13d831a6365f6c9b4ce772b5b01b4dced309)
> PRODSEC-5480 - Bump jsoup version from 1.13.1 to 1.14.2

- pom.xml
(cherry picked from commit ee07bb635fb9a3099e6eb57c741aeb0ebb203730)
> [PRODSEC-5795] Bump surf-webscripts to 8.25 (#803)

- pom.xml
(cherry picked from commit 20a617adef6c442a798616295e2f153e3fa8d5d6)
> [MNT-22680] Bump surf-webscripts to 8.26 (#814)

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/version/RecordableVersionServiceImpl.java
- repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
- repository/src/main/java/org/alfresco/repo/version/Version2ServiceImpl.java
- repository/src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java
* Set association index on new version creation
* Unit test to verify the child assoc index is set on version nodes
> MNT-22715 - Document Version Issue

- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/parse-args.lib.js
(cherry picked from commit 2561ad6f2bb5d4beb0cb0286932111a9bc25f0d6)
> [MNT-21551] Handle links path with a changed root-node (#824)

- data-model/src/main/java/org/alfresco/service/cmr/repository/RestoreInProgressException.java
- remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/RestoreInProgressException.java
- remote-api/src/main/resources/alfresco/public-rest-context.xml
Adds the RestoreInProgressException and configures it to throw a 409 (STATUS_CONFLICT) error by the rest api.
> ACS-2331 Add RestoreInProgressException

- remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/ContentStorageInformationImplTest.java
Fixing a possible NPE when no body for POST requests provided at all.
> ACS-2236: Fixing NPE when no body provided for POST requests.

- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/support-tools/admin-nodebrowser.get.html.ftl
* MNT-21506: sanitize username on nodeBrowser Repo
(cherry picked from commit a2d9afcecc65fbbbfb5868334f3b9ba92be38d32)
> MNT-21506: sanitize username on nodeBrowser Repo (#756)

- repository/src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
- repository/src/main/resources/alfresco/repository.properties
* Cron rate changed
* Message now an ERROR rather than DEBUG about T-Engine/T-Router being down
> ACS-2412 Log files flooded with transformation option messages when config is misconfigured

- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsStorageInfoRelation.java
- thanks @mpichura for detailed verification of ACS-2391 and feedback
- fix blatant typo in https://github.com/Alfresco/alfresco-community-repo/pull/863
- Note: e2e API sanity check will be added as part of ACS-2406
> ACS-2391: ACS-2391: StorageObjectProps - add version content specific endpoints

- remote-api/src/main/java/org/alfresco/rest/api/Renditions.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/RenditionsImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRenditionsRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionRenditionsRelation.java
- remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/Params.java
- remote-api/src/main/java/org/alfresco/rest/framework/webscripts/ResourceWebScriptDelete.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
- repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2.java
- repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
- repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
* Code to reject zero byte renditions
* Addition of DELETE /nodes/{nodeId}/renditions/{renditionId} and DELETE /nodes/{nodeId}/versions/{versionId}/renditions/{renditionId} end points
> MNT-22696 Replace Rendition REST API

- .travis.yml
(cherry picked from commit 2032396a5150e24fbba37056143bb4bea8f24736)
> build fix branches

- pom.xml
REST API Explorer version bump to 7.2.0-A3
> REST API Explorer -Ax release

- pom.xml
(cherry picked from commit c8d4106d73533307afc779af7bff16535703c802)
> MNT-22388 Upgrade to org.apache.pdfbox:pdfbox:2.0.23

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/GetSitesTests.java
(cherry picked from commit 1b42d80f940b7bf679a5a836ae4d36b598e92c0a)
> MNT-22807: improve sitesTest test (#925)

- pom.xml
Reverts Alfresco/alfresco-community-repo#957
> Revert "ACS-2476 Bump Camel version to 3.8.0"

- remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
- remote-api/src/test/resources/alfresco-global.properties
[ACS-1982] Extended tests for REST integration tests
[ACS-1982]: https://alfresco.atlassian.net/browse/ACS-1982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add further tests for ReST integration tests

- pom.xml
- repository/src/main/java/org/alfresco/repo/content/transform/LocalPipelineTransform.java
- repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
- repository/src/main/java/org/alfresco/repo/rendition2/LocalSynchronousTransformClient.java
- repository/src/main/java/org/alfresco/repo/rendition2/LocalTransformClient.java
- repository/src/main/resources/alfresco/rendition-services2-context.xml
- repository/src/main/resources/alfresco/repository.properties
* First cut at code using directAccessUrl in transform options.
* Using t-model 1.4.11, which includes this option in the t-config if supported
> ACS-2493/ACS-2494 Repo Transform requests using a DAU

- pom.xml
Reverts Alfresco/alfresco-community-repo#995
> Revert "Bump dependency.tas-restapi from 1.71 to 1.77"

- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/upload/upload.post.js
…dn't extract it form temporary node.
> ACS-2658 Fix missing metadata extraction while uploading new version

- repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
Reverts Alfresco/alfresco-community-repo#1103
> Revert "ATS-988 Intermittent test failure: End-to-End Tests - AI-Renditions"

- repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
Reverts Alfresco/alfresco-community-repo#1148
> Revert "Revert "ATS-988 Intermittent test failure: End-to-End Tests - AI-Renditions""

- amps/share-services/src/main/java/org/alfresco/slingshot/web/scripts/NodeBrowserScript.java
PRODSEC-6115: Removing Exception Stack
> PRODSEC-6115: Removing Exception Stack

- repository/src/main/resources/alfresco/subsystems/email/InboundSMTP/inboundSMTP.properties
- Update the email.server.domain property to use example.com
> [MNT-22085] Change default email domain

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/workflow/processes/GetProcessSanityTests.java
- remote-api/src/main/java/org/alfresco/rest/workflow/api/impl/ProcessesImpl.java
> PRODSEC-6261 Fix workflow api bola - Backporting

- .travis.yml
(cherry picked from commit 3990bc9db4a5768c33a0c1836a09a8f2fb1cd38d)
> [ACS-3271] Update MySQL 5.7.23 tests to 5.7.28 version (#1209)

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
- pom.xml
- remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
Happy path tests for creating and retrieving rules.
> ACS-3227 Simple rules tests.

- remote-api/src/main/java/org/alfresco/rest/framework/core/ResourceLookupDictionary.java
Fix for https://alfresco.atlassian.net/browse/ACS-3355
> ACS-2827: Fix Resources and Property Exceptions

- repository/src/main/java/org/alfresco/repo/exporter/ExporterComponent.java
- repository/src/main/java/org/alfresco/service/cmr/view/ExporterContext.java
- repository/src/main/java/org/alfresco/service/cmr/view/ExporterService.java
- repository/src/main/resources/alfresco/import-export-context.xml
- repository/src/test/java/org/alfresco/repo/exporter/ExporterComponentTest.java
* MNT-23087 - Split the export list into several smaller list for better performance
(cherry picked from commit 9c98f7b0fbc58fcceab34ae9186a9606984c5a12)
> Fix/mnt 23087 export of records failing (#1333)

- pom.xml
Reverts Alfresco/alfresco-community-repo#1414
> Revert "Bump dependency.poi.version from 5.2.2 to 5.2.3"

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/jscript/app/JSONConversionComponent.java
Resolved error while loading records subcategory with cutoff.
> MNT-22233 resolved error while loading subcategory with cutoff.

- remote-api/src/main/java/org/alfresco/rest/api/model/RepositoryInfo.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/DiscoveryApiTest.java
Reverts Alfresco/alfresco-community-repo#1423.
> Revert "Feature/acs 3560 discovery api for custom embedded workflow license"

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
https://alfresco.atlassian.net/browse/ACS-3427
> ACS-3427: Add GET e2es for actions and conditions

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
- pom.xml
https://alfresco.atlassian.net/browse/ACS-3601
> ACS-3601: Add unlink e2es

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
- pom.xml
- remote-api/src/main/java/org/alfresco/rest/api/Rules.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleExecution.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleExecutionsRelation.java
- remote-api/src/main/resources/alfresco/public-rest-context.xml
- remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
https://alfresco.atlassian.net/browse/ACS-3525
This PR covers only basic E2E test. Further E2Es will be added within separate task.
> ACS-3525: API for manual triggering rules on a folder

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
If a user does not have access to a rule set applied to a node then it will be excluded from the results, but the user will be able to see the list of other rule sets.
Also add E2E tests for permissions when viewing rule sets.
> ACS-3657 Allow returning partial list of rule sets.

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapper.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapperTest.java
This PR only covers validation for condition comparator values in compare property condition.
> ACS-3855: Add validation for rule condition comparator.

- repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java
(cherry picked from commit 295a8f7ba2925308b54a5599289ab0ea2609bb3b)
> MNT-23276 - The null facet name should be considered (#1540)

- repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
✅ `com-r` build: https://app.travis-ci.com/github/Alfresco/alfresco-community-repo/builds/257647983
✅ `ent-r` build: https://app.travis-ci.com/github/Alfresco/alfresco-enterprise-repo/builds/257643835
✅  `ent-s` build: https://app.travis-ci.com/github/Alfresco/alfresco-enterprise-share/builds/257643970
✅  `acs-p` build: https://app.travis-ci.com/github/Alfresco/acs-packaging/builds/257644732
Thanks for reporting the situation @pzhyland !
> MNT-22485: added missing tables to query

- repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
- repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
- repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
- repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
- repository/src/main/resources/alfresco/repository.properties
- repository/src/main/resources/alfresco/script-services-context.xml
- repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
(cherry picked from commit f391cfa38c2bdc11e8a2eeaea257f4dcf04f0732)
> [MNT-23158] Scripts limits configuration and optimization (#1519)

- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/site/membership/potentialmembers.get.js
(cherry picked from commit 93a7790d44f06ffe33a9b9c7d4f985a6ef10ff1b)
> MNT-23204:  Group Search (#1558)

- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryModel.java
- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Categories.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesRestTest.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CreateCategoriesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/DeleteCategoriesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/GetCategoriesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/UpdateCategoriesTests.java
- remote-api/src/main/java/org/alfresco/rest/api/Categories.java
- remote-api/src/main/java/org/alfresco/rest/api/categories/CategoriesEntityResource.java
- remote-api/src/main/java/org/alfresco/rest/api/categories/SubcategoriesRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/model/Category.java
- remote-api/src/test/java/org/alfresco/rest/api/categories/CategoriesEntityResourceTest.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
https://alfresco.atlassian.net/browse/ACS-4029
> ACS-4029: Update a category name - PUT /categories/{categoryId}

- amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/security/rm-method-security.properties
- data-model/src/main/java/org/alfresco/service/cmr/repository/NodeService.java
- repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
- repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
- repository/src/main/java/org/alfresco/repo/node/db/DbNodeServiceImpl.java
- repository/src/main/java/org/alfresco/repo/security/authority/AuthorityDAOImpl.java
- repository/src/main/java/org/alfresco/repo/version/NodeServiceImpl.java
- repository/src/main/java/org/alfresco/repo/virtual/bundle/VirtualNodeServiceExtension.java
- repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
- repository/src/main/resources/alfresco/public-services-security-context.xml
* MNT-23290 - Change query to get the root groups
(cherry picked from commit d785b100df430408d441e3a6c8d5e200f292219e)
> Fix/mnt 23290 slow group membership (#1637)

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/model/behaviour/RecordsManagementSearchBehaviour.java
AGS - Missing properties after moving record between categories
> MNT-23263 Changes done for missing properties after moving record between categories

- remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
(cherry picked from commit 88a08545482729676b25cd339cbcc65e8e26fcff)
> [MNT-23379] Set site manager permission if node belongs to a site and inheritance flag is disabled (#1657)

- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryLinkBodyModel.java
- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Node.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesRestTest.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/GetCategoryLinksTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/ListCategoriesForNodeTests.java
- remote-api/src/main/java/org/alfresco/rest/api/Categories.java
- remote-api/src/main/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
- remote-api/src/main/java/org/alfresco/rest/framework/resource/SerializablePagedCollection.java
- remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/ArrayListPage.java
- remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/ListPage.java
- remote-api/src/test/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelationTest.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
- remote-api/src/test/java/org/alfresco/rest/framework/resource/parameters/ArrayListPageTest.java
https://alfresco.atlassian.net/browse/ACS-4033
GET /nodes/{nodeId}/category-links
> ACS-4033: List linked categories for a particular node

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/ListCategoriesForNodeTests.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
- remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/InvalidNodeTypeException.java
- remote-api/src/main/resources/alfresco/messages/rest-framework-messages.properties
- remote-api/src/main/resources/alfresco/public-rest-context.xml
- remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
- remote-api/src/test/resources/test-rest-context.xml
https://alfresco.atlassian.net/browse/ACS-4362
> ACS-4362: Fix returned HTTP error status for invalid note type

- repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
- repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
- repository/src/main/resources/alfresco/events2-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/repo/event2/EventGeneratorDisabledTest.java
- repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
* Added configuration repo.event2.enabled (true by default)
* Prevent the event2 behaviours from binding on bootstrap if disabled
* Implemented enable and disable methods that can be called in runtime on EventGenerator - this disables/enables the binded behaviours
> MNT-23411 Option to disable events2

- repository/src/main/java/org/alfresco/repo/bulkimport/metadataloaders/AbstractMapBasedMetadataLoader.java
(cherry picked from commit 781f0455033b460ec331391485202d3779db6085)
> [MNT-23414] Bulk import - convert empty values to null for certain types (#1688)

- repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
- repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
- repository/src/main/resources/alfresco/events2-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/repo/event2/EventGeneratorDisabledTest.java
- repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
* Added configuration to disable events2 so the behaviours are not bootstrapped. Additionally added options to enable/disable on runtime
* Added unit test
(cherry picked from commit 9637d514ddc972a47e89cdd2be27a94a023e26b3)
> MNT-23411 Option to disable events2 (#1703)

- .github/workflows/ci.yml
Replace `contains` with `startsWith` for better branch detection.
> ACS-3750 Improve branch detection in if conditions

- .github/workflows/master_release.yml
> ACS-3750 Use set Git token instead of cached one

- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestTagModel.java
- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/coreAPI/RestCoreAPI.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/CreateTagsTests.java
- remote-api/src/main/java/org/alfresco/rest/api/Tags.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/model/Tag.java
- remote-api/src/main/java/org/alfresco/rest/api/tags/TagsEntityResource.java
- remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
- remote-api/src/test/java/org/alfresco/rest/api/TagsUnitTests.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
- remote-api/src/test/java/org/alfresco/rest/api/tags/TagsEntityResourceTest.java
- repository/src/main/java/org/alfresco/repo/tagging/TaggingServiceImpl.java
- repository/src/main/java/org/alfresco/service/cmr/tagging/TaggingService.java
- repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
- repository/src/test/java/org/alfresco/repo/tagging/TaggingServiceImplUnitTest.java
https://alfresco.atlassian.net/browse/ACS-4026
> ACS-4026: Create orphaned tag with POST /tags

- remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
[ACS-3960][ACS-4339] Count is only returned for a tag if it is greater than zero
[ACS-3960]: https://alfresco.atlassian.net/browse/ACS-3960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ACS-3960][ACS-4339] Count is only returned for a tag if it is greater than zero

- .github/workflows/ci.yml
- scripts/ci/docker-compose/docker-compose-db.yaml
* Added MYSQL_PARAMS variable that allow us to set different values for 5.7.28 and mySQL 8
> ACS-4653 GHA - Fix mySQL tests

- packaging/tests/tas-integration/pom.xml
- pom.xml
- repository/pom.xml
> ACS-4844 Dependency alignment after Keycloak migration

- remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
- remote-api/src/main/resources/alfresco/public-rest-context.xml
- remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
Added TagId Validation for Get and Delete methods
> [ACS-3916][ACS-3917] Added TagId Validation for Get and Delete methods

- amps/share-services/pom.xml
- repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
https://alfresco.atlassian.net/browse/ACS-4857
> ACS-4857: Lookup for root tag in DB and NOT using search engine

- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceConfig.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
- repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
* Unify http client for all IDS related activities
* Restore connection configuration
* Restore TLS/mTLS configuration
> ACS-4893 ACS-4890 Restore connection/TLS/mTLS IDS configuration

- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryModel.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesPathTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesRestTest.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/model/Category.java
- remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
https://alfresco.atlassian.net/browse/ACS-4966
This PR is about adding path param to Categories API.
> ACS-4966 Add path to Category API

- pom.xml
Bumping Spring to the latest available 5.x version.
> ACS-5083 Bump Spring to 5.3.27

- repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
- repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
(cherry picked from commit f83328f7b096cf0d712e168c147b992575ddb0c9)
> [MNT-23550] Always disable behaviours to prevent unexpected modifier changes (#1898)

- packaging/tests/tas-restapi/pom.xml
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/RenditionIntegrationTests.java
Ref. [ACS-5087](https://alfresco.atlassian.net/browse/ACS-5087)
[ACS-5087]: https://alfresco.atlassian.net/browse/ACS-5087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ACS-5087 Add more attempts to create a folder in RenditionIntegrationTests

- scripts/ci/update_downstream.sh
It could help to indicate what exactly is updated on upstream repository.
> Change commit message to more meaningful.

- pom.xml
> ACS-5209: Propagate alfresco-messaging-repo update to 1.2.22

- repository/src/main/java/org/alfresco/repo/security/sync/ldap/LDAPUserRegistry.java
(cherry picked from commit 07c734203217e3d00395fa0bb91fde57b3f9bd10)
> [MNT-23665] Removed search controls count limit (#1936)

- repository/src/main/java/org/alfresco/repo/policy/TransactionBehaviourQueue.java
(cherry picked from commit 689e6a23fa3d76a91ceff9df154d9a368d9da92d)
> [MNT-23642] Add error messages (#2019)

- pom.xml
- bump TAS Utility version
https://alfresco.atlassian.net/browse/ACS-4799
> ACS-4799: E2Es - Elasticsearch query feature expansion - boosts

- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestPersonFavoritesModel.java
- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/search/SearchNodeModel.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/favorites/GetFavoritesTests.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/FavouritesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/model/Favourite.java
- remote-api/src/main/java/org/alfresco/rest/api/search/impl/SearchMapper.java
- remote-api/src/test/java/org/alfresco/rest/api/search/SearchMapperTests.java
These small additions have been requested by MobileApps team to let them lower down number of API calls when performing some sort of bulk operations.
Search E2E tests are coming in https://github.com/Alfresco/SearchServices project once this PR is merged.
> Feature/ACS-5624 Search and Favorites API enhancements

- remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
- remote-api/src/main/java/org/alfresco/rest/api/DirectAccessUrlHelper.java
- remote-api/src/main/java/org/alfresco/rest/api/Nodes.java
- remote-api/src/main/java/org/alfresco/rest/api/Renditions.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/DeletedNodesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/RenditionsImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/model/DirectAccessUrlRequest.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRenditionsRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionRenditionsRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodesEntityResource.java
- remote-api/src/main/java/org/alfresco/rest/api/trashcan/TrashcanEntityResource.java
- remote-api/src/main/java/org/alfresco/rest/api/trashcan/TrashcanRenditionsRelation.java
- repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
- repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
- repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
- repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
Adds optional file name parameter for all direct access url requests https://github.com/Alfresco/alfresco-community-repo/issues/2064
> File name param for direct access url requests

- remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
- remote-api/src/main/java/org/alfresco/rest/api/DirectAccessUrlHelper.java
- remote-api/src/main/java/org/alfresco/rest/api/Nodes.java
- remote-api/src/main/java/org/alfresco/rest/api/Renditions.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/DeletedNodesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/RenditionsImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/model/DirectAccessUrlRequest.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRenditionsRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionRenditionsRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsRelation.java
- remote-api/src/main/java/org/alfresco/rest/api/nodes/NodesEntityResource.java
- remote-api/src/main/java/org/alfresco/rest/api/trashcan/TrashcanEntityResource.java
- remote-api/src/main/java/org/alfresco/rest/api/trashcan/TrashcanRenditionsRelation.java
- repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
- repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
- repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
- repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
Adds optional file name parameter for all direct access url requests https://github.com/Alfresco/alfresco-community-repo/issues/2064
> File name param for direct acccess url requests

- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/collaboration/tagQuery.get.js
- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/categorynode.get.js
- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/images.get.js
(cherry picked from commit fcf3e005e441a4bd74febd071712e1b9b4f6e38e)
> MNT-23763 Fix image preview webscript for use with ES.

- pom.xml
- repository/pom.xml
Solution eliminating test failures in alfresco-enterprise-repo: https://github.com/Alfresco/alfresco-enterprise-repo/actions/runs/5669575699/job/15390101
> ACS-5449 Add commons-net dependency to main pom.xml file

- .github/workflows/ci.yml
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java
Could not replicate error from: https://alfresco.atlassian.net/browse/ACS-5020 did not happen even once.
But there was other failure happening couple of times which after re-runing turned green. 
It is not connected with that test class which I have investigate but it is from the same job AGS Community Rest API Tests:
Apart from this I have only reduced PMD issues. And everything passes tests.
> ACS-5020 Investigate test failures

- data-model/src/main/java/org/alfresco/service/cmr/repository/DirectAccessUrl.java
- repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
- repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
This will cause it to be returned in the response
> Add file name to DirectAccessUrl

- remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- remote-api/src/main/resources/alfresco/public-rest-context.xml
- remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
(cherry picked from commit 1d56eb1dd1ed11ec336b4a17b04e2753aeff8689)
> [MNT-23816] Prevent rules aspect removal when there are existing rules (#2114)

- repository/src/main/java/org/alfresco/schedule/ScheduledJobLockExecuter.java
- repository/src/test/java/org/alfresco/AppContextExtraTestSuite.java
- repository/src/test/java/org/alfresco/schedule/AbstractScheduledLockedJobTest.java
- repository/src/test/java/org/alfresco/schedule/Cleaner.java
- repository/src/test/java/org/alfresco/schedule/CleanerJob.java
- repository/src/test/resources/alfresco/schedule/test-schedule-context.xml
* [MNT-23509] Add lock callback to refreshLock method
* [MNT-23509] Added unit test
* [MNT-23509] PMD scan improvements
(cherry picked from commit 27186a56b899cc7de09b27a4d67dcdd84c2cf5ae)
[MNT-23509]: https://alfresco.atlassian.net/browse/MNT-23509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-23509]: https://alfresco.atlassian.net/browse/MNT-23509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-23509]: https://alfresco.atlassian.net/browse/MNT-23509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MNT-23509] Add lock callback to refreshLock method (#2030)

- repository/src/test/java/org/alfresco/repo/event2/DirectEventGeneratorTest.java
- repository/src/test/java/org/alfresco/repo/event2/EnqueuingEventGeneratorTest.java
- repository/src/test/java/org/alfresco/repo/event2/EventGeneratorDisabledTest.java
- repository/src/test/java/org/alfresco/repo/event2/EventGeneratorTest.java
- repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
- fixing failing tests in enterprise-repo
> ACS-5451: Toggle for direct Event sending

- pom.xml
> ACS-5943 Bump ATS to 4.1.0-A1 / 3.1.0-A1

- pom.xml
> ACS-5944 Bump ATS to the latest -Mx

- repository/src/main/resources/alfresco/repository.properties
https://alfresco.atlassian.net/browse/ACS-4778
> [ACS-4778] Added usr:user nodeType for exclusion for event publishing

- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/search/RestRequestFieldsModel.java
- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/search/RestRequestHighlightModel.java
- added prefix and postfix to field model (TAS)
More info: https://alfresco.atlassian.net/browse/ACS-6070
> ACS-6070: Support for highlighting prefix and postfix

- core/src/main/java/org/alfresco/web/scripts/servlet/X509ServletFilterBase.java
https://alfresco.atlassian.net/browse/MNT-23896
> [MNT-23896] run handleClientAuth only when this.enforce variable is true

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/email/RFC822MetadataExtracter.java
https://alfresco.atlassian.net/browse/MNT-23933
> [MNT-23933] Fixed Null Pointer Exception

- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/search/RestRequestFieldsModel.java
- added snippetCount, fragmentSize and mergeContiguous to highlighting field model
More info: https://alfresco.atlassian.net/browse/ACS-6075
> ACS-6075: Highlight snippet control parameters

- amps/ags/rm-community/rm-community-repo/.env
- packaging/tests/environment/.env
- pom.xml
- scripts/ci/docker-compose/docker-compose-db.yaml
- scripts/ci/docker-compose/docker-compose.yaml
> MNT-24063 Bump ActiveMQ to 5.18.3

- amps/ags/rm-community/rm-community-repo/.env
- amps/ags/rm-community/rm-community-repo/pom.xml
- packaging/tests/environment/.env
- pom.xml
- scripts/ci/docker-compose/docker-compose-db.yaml
- scripts/ci/docker-compose/docker-compose.yaml
> MNT-24063 Bump ActiveMQ to 5.17.6

- pom.xml
> ACS-6192 Bump org.json:json to 20231013

- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/fileplans/FilePlanTests.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/utils/AlphabeticalPriorityInterceptor.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/resources/testng.xml
- repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
- repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
- repository/src/test/java/org/alfresco/repo/security/SecurityTestSuite.java
- repository/src/test/java/org/alfresco/util/test/junitrules/RetryAtMostRule.java
- repository/src/test/java/org/alfresco/util/test/junitrules/RetryAtMostRuleTest.java
> MNT-24063 Fix AGS community tests & FixedAclUpdaterTest

- remote-api/src/main/java/org/alfresco/repo/web/scripts/servlet/RemoteUserAuthenticatorFactory.java
- remote-api/src/main/resources/alfresco/web-scripts-application-context.xml
- repository/src/main/java/org/alfresco/repo/security/authentication/external/AdminConsoleAuthenticator.java
- repository/src/main/java/org/alfresco/repo/security/authentication/external/DefaultAdminConsoleAuthenticator.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacade.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/SpringBasedIdentityServiceFacade.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/admin/AdminConsoleAuthenticationCookiesService.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/admin/AdminConsoleHttpServletRequestWrapper.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/admin/IdentityServiceAdminConsoleAuthenticator.java
- repository/src/main/resources/alfresco/authentication-services-context.xml
- repository/src/main/resources/alfresco/subsystems/Authentication/external/external-authentication-context.xml
- repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
- repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
- repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/admin/AdminConsoleAuthenticationCookiesServiceUnitTest.java
- repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/admin/AdminConsoleHttpServletRequestWrapperUnitTest.java
- repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/admin/IdentityServiceAdminConsoleAuthenticatorUnitTest.java
E2E test via alfresco-terraform-pipeline : https://github.com/Alfresco/terraform-alfresco-pipeline/actions/runs/7164988834/job/19507355210
> MNT-23880 Integrate the Alfresco Admin Console with the IDS

- repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
- repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
* Disabled audibled and versionable behaviour on add and remove pending acl aspect and properties
* Added validations to the unit test to assert modification date is not changed
> [MNT-24085] - Fixed ACL Updater job is updating the cm:modifier details

- pom.xml
https://alfresco.atlassian.net/browse/ACS-6444
> updated swagger-ui version to 4.1.3

- remote-api/src/main/java/org/alfresco/repo/web/scripts/solr/NodesMetaDataGet.java
> Map includeChildAssociations request parameter

- pom.xml
https://alfresco.atlassian.net/browse/ACS-6113
> ACS-6113: Fix secondary parents to never be set to null

- pom.xml
https://alfresco.atlassian.net/browse/PRODSEC-8282
> [APPS-2576] fix for Spring Web Vulnerability

- pom.xml
https://alfresco.atlassian.net/browse/ACS-7212
> [ACS-7212]-json-smart issue fixed

- pom.xml
- repository/src/main/java/org/alfresco/repo/template/XSLTProcessor.java
- repository/src/test/java/org/alfresco/repo/rendition/executer/XSLTRenderingEngineTest.java
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* bump xalan
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: bump xalan version
* MNT-24250: alfresco.3
* MNT-24250: alfresco.3
* MNT-24250: alfresco.3
* MNT-24250: alfresco.3
* MNT-24250: alfresco.3
* MNT-24250: 2.7.3 official
* MNT-24250: 2.7.3-alfresco.3
* MNT-24250: 2.7.3-alfresco.3
* MNT-24250: 2.7.3-alfresco.3
* MNT-24250: 2.7.3-alfresco.3
* …
> MNT-24250: bump xalan version (#2497)

- pom.xml
https://alfresco.atlassian.net/browse/ACS-7210
> [ACS-7210]- guava-29.0 issue

- scripts/ci/docker-compose/docker-compose.yaml
> ACS-7565 Bump Keycloak to 24.0.2

- pom.xml
> ACS-7676 Bump snakeyaml version to 2.2

- pom.xml
> ACS-7743 Bump Spring to 5.3.34

- pom.xml
> ACS-7745 Bump Spring to 5.3.34

- scripts/ci/docker-compose/docker-compose.yaml
> ACS-7744 Bump Keycloak to 24.0.3

- pom.xml
As per title, bumping to the latest non-major upgrade version.
> ACS-7884 Bump cxf to 3.6.3

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/capability/impl/CreateCapability.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/capability/policy/CreatePolicy.java
- amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/integration/record/CreateRecordTest.java
https://hyland.atlassian.net/browse/MNT-24195
> [MNT-24195] Added fix for ags capability issue

- pom.xml
Wrong branch name. It is for 7.3.N
> [ACS-7896] Bump AIS/ATS 5.1.2/4.1.2

- scripts/ci/docker-compose/docker-compose.yaml
> ACS-7569 Test with Keycloak 24.0.3

- pom.xml
As per title.
To include: https://github.com/Alfresco/alfresco-tas-utility/pull/108.
> ACS-8114 Bump TAS utility to 5.0.1

- remote-api/src/main/java/org/alfresco/repo/web/scripts/solr/NodesMetaDataGet.java
(cherry picked from commit 3b574c56dc1537bb35164b887938802804e2f1ff)
> MNT-24477 - Map includeChildAssociations request parameter

- amps/ags/rm-community/rm-community-rest-api-explorer/src/main/webapp/definitions/gs-core-api.yaml
https://hyland.atlassian.net/browse/APPS-2853
> [APPS-2853] Swagger Documentation for Retention Schedule V1 APIs

- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/core/RestAPIFactory.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/retentionschedule/RetentionSchedule.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/retentionschedule/RetentionScheduleActionDefinition.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/retentionschedule/RetentionScheduleCollection.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/retentionschedule/RetentionScheduleEntry.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/requests/gscore/GSCoreAPI.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/requests/gscore/api/RetentionScheduleAPI.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/retentionschedule/RetentionScheduleTests.java
- amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/rm-public-rest-context.xml
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/disposition/DispositionServiceImpl.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/impl/ApiNodesModelFactory.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/model/RetentionSchedule.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/model/RetentionScheduleActionDefinition.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/retentionschedule/RetentionScheduleRelation.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/retentionschedule/package-info.java
- amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/legacy/service/DispositionServiceImplTest.java
- amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/disposition/RetentionScheduleModelUnitTest.java
- amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/model/apiNodes/ApiNodesModelFactoryUnitTest.java
https://hyland.atlassian.net/browse/APPS-2836
https://hyland.atlassian.net/browse/APPS-2837
> [APPS-2836][APPS-2837] Retention Schedule POST and GET API

- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceConfig.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
- repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
- repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication.properties
- repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBeanTest.java
Based on the following draft PR: https://github.com/Alfresco/alfresco-community-repo/pull/2673
> ACS-8048 Fix HXIAM access token validation issues

- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/retentionschedule/RetentionScheduleActionDefinition.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/retentionschedule/RetentionScheduleStepTests.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/impl/ApiNodesModelFactory.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/model/RetentionScheduleActionDefinition.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/model/RetentionSteps.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/retentionschedule/RetentionScheduleActionRelation.java
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/retentionschedule/RetentionScheduleRelation.java
- amps/ags/rm-community/rm-community-rest-api-explorer/src/main/webapp/definitions/gs-core-api.yaml
https://hyland.atlassian.net/browse/APPS-2909
https://hyland.atlassian.net/browse/APPS-2907
https://hyland.atlassian.net/browse/APPS-2905
https://hyland.atlassian.net/browse/APPS-2906
> [APPS-2905][APPS-2906][APPS-2907][APPS-2909] Defect fixes in Retention Schedule V1 API's

- .github/workflows/ci.yml
- amps/ags/README.md
- amps/ags/ci/scripts/getLogs.sh
- packaging/tests/scripts/start-compose.sh
- packaging/tests/scripts/stop-compose.sh
- packaging/tests/scripts/wait-for-alfresco-start.sh
> ACS-8352 Migrate to docker compose v2

- .github/workflows/ci.yml
- amps/ags/README.md
- amps/ags/ci/scripts/getLogs.sh
- packaging/tests/scripts/start-compose.sh
- packaging/tests/scripts/stop-compose.sh
- packaging/tests/scripts/wait-for-alfresco-start.sh
> [ACS-8352] Migrate to docker compose v2

- core/pom.xml
- core/src/main/java/org/alfresco/util/GUID.java
- data-model/src/main/java/org/alfresco/repo/security/authentication/InMemoryTicketComponentImpl.java
- mmt/pom.xml
- mmt/src/main/java/org/alfresco/repo/module/tool/ModuleManagementTool.java
- repository/src/main/java/org/alfresco/repo/quickshare/QuickShareServiceImpl.java
- repository/src/main/java/org/alfresco/repo/security/person/SplitPersonCleanupBootstrapBean.java
- repository/src/test/java/org/alfresco/repo/quickshare/QuickShareServiceIntegrationTest.java
https://hyland.atlassian.net/browse/PRODSEC-9364
> [PRODSEC-9364] added java-uuid-generator

- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/impl/SearchTypesFactory.java
https://hyland.atlassian.net/browse/MNT-24310
> [MNT-24310] Fix AGS Rest API returning non RM objects

- packaging/war/pom.xml
- packaging/war/src/main/webapp/index.jsp
https://hyland.atlassian.net/browse/PRODSEC-8922
> [PRODSEC-8922] fix xss vulnerability

- data-model/pom.xml
- packaging/tests/tas-restapi/pom.xml
- pom.xml
- repository/pom.xml
- repository/src/main/java/org/alfresco/repo/virtual/bundle/VirtualNodeServiceExtension.java
Propagation tests:
- [enterprise-repo](https://github.com/Alfresco/alfresco-enterprise-repo/actions/runs/9992615630)
- [enterprise-share](https://github.com/Alfresco/alfresco-enterprise-share/actions/runs/9993917130) (See [workarounds](https://github.com/Alfresco/alfresco-enterprise-share/compare/release/7.3.2...feature/ACS-8298_bump-bouncycastle-7.3.2) to run tests)
- [acs-packaging](https://github.com/Alfresco/acs-packaging/actions/runs/9992936113)
This PR is based on the following PRs for the master branch:
- https://github.com/Alfresco/alfresco-community-repo/pull/2682
- https://github.com/Alfresco/alfresco-community-repo/pull/2422
- https://github.com/Alfresco/alfresco-community-repo/pull/2073
> ACS-8298 Bump bouncycastle, commons-io, poi, tika, apache-compress, xmlbeans

- data-model/pom.xml
- packaging/tests/tas-restapi/pom.xml
- pom.xml
- repository/pom.xml
- repository/src/main/java/org/alfresco/repo/virtual/bundle/VirtualNodeServiceExtension.java
Backported changes from https://github.com/Alfresco/alfresco-community-repo/pull/2796
Propagation tests:
- [alfresco-enterprise-repo](https://github.com/Alfresco/alfresco-enterprise-repo/actions/runs/10040613485)
- [alfresco-enterprise-share](https://github.com/Alfresco/alfresco-enterprise-share/actions/runs/10041516672)
- [acs-packaging](https://github.com/Alfresco/acs-packaging/actions/runs/10040729391)
> ACS-8298 Bump bouncycastle, commons-lang3, commons-io, commons-compress, xmlbeans, tika, poi

- amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/capability/rm-capabilities-recordfolder-context.xml
https://hyland.atlassian.net/browse/MNT-24292
> [MNT-24292] fix for delete vulnerability

- repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
(cherry picked from commit a3f6e13a7c7c0b07f653ca700c74374bc67af951)
> MNT-24503 - FixedAclUpdater Job - Skip count if maxSize is set (#2809)

- pom.xml
> ACS-8421 Bump Transform Core to 5.1.4-A1 + Service to 4.1.4-A1

- repository/src/main/java/org/alfresco/repo/download/DownloadStorage.java
- repository/src/main/java/org/alfresco/repo/download/ZipDownloadExporter.java
https://hyland.atlassian.net/browse/MNT-24124
> [MNT- 24124] Adding node references in DownloadStorage and ZipDownloadExporter files.

- pom.xml
> PRODDEL-8304 Bump API Explorer to 23.3.0

- .github/workflows/ci.yml
As per title, ref https://hyland.atlassian.net/browse/ACS-8642
> ACS-8670 Do not fail on SCA findings

- repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
https://hyland.atlassian.net/browse/MNT-23264
> [MNT-23264] script execution error

- repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
Reverts Alfresco/alfresco-community-repo#2900
> Revert "[MNT-23264] script execution error"

- pom.xml
Reverts Alfresco/alfresco-community-repo#2904
> Revert "Bump dependency.log4j.version from 2.23.1 to 2.24.0"

- repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
https://hyland.atlassian.net/browse/MNT-23264
> [MNT-23264] Added fix for running job as system user

- core/src/main/java/org/alfresco/httpclient/HttpClientException.java
- repository/src/main/java/org/alfresco/repo/search/impl/solr/AbstractSolrQueryHTTPClient.java
- repository/src/test/java/org/alfresco/repo/search/impl/solr/AbstractSolrQueryHTTPClientTest.java
Fixing https://hyland.atlassian.net/browse/MNT-24346
> MNT-24346: Fix "0" return status code in Search API when Solr is unavailable.

- pom.xml
Surf-webscript version 9.4 ( with Spring 6.1.13 version )
> Update surf-webscript version to 9.4

- pom.xml
Update aos version to 4.0.0-A1 with Spring 6.1 upgrade
> Update aos version

- scripts/ci/docker-compose/docker-compose.yaml
> [ACS-8862] Bump Keycloak to 25.0.6

- packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/People.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/people/preferences/GetPeoplePreferenceFullTests.java
- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/people/preferences/GetPeoplePreferenceSanityTests.java
- remote-api/src/main/java/org/alfresco/rest/api/Preferences.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/PreferencesImpl.java
- remote-api/src/main/java/org/alfresco/rest/api/people/PersonPreferencesRelation.java
- remote-api/src/main/java/org/alfresco/rest/framework/webscripts/ResourceWebScriptPut.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/TestUserPreferences.java
- remote-api/src/test/java/org/alfresco/rest/api/tests/client/PublicApiClient.java
alfresco-enterprise-repo PR: https://github.com/Alfresco/alfresco-enterprise-repo/pull/2278
rest-api-explorer PR: https://github.com/Alfresco/rest-api-explorer/pull/219
> ACS-9023 Implement PUT method - Preferences API

- amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/patch/v33/RMv33HoldAuditEntryValuesPatchUnitTest.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/AuditImpl.java
- repository/src/main/java/org/alfresco/repo/audit/AuditComponent.java
- repository/src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java
- repository/src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java
- repository/src/main/java/org/alfresco/repo/domain/CrcHelper.java
- repository/src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java
- repository/src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java
- repository/src/main/java/org/alfresco/repo/domain/propval/PropertyStringValueEntity.java
- repository/src/main/java/org/alfresco/service/cmr/audit/AuditService.java
This reverts commit cabc38b386cbb400a901047e7a101b619107d31b.
> Revert "[MNT-24137] Audit Issue Internal Server Error fix (#2786)"

- .github/workflows/ci.yml
- updated test suites to verify support of MariaDB 10.11
> ACS-9113 Verify Supported Platform for 25.1

- amps/ags/rm-community/rm-community-rest-api-explorer/src/main/webapp/definitions/gs-core-api.yaml
[APPS-3106] Removed special characters from yaml files
[APPS-3106]: https://hyland.atlassian.net/browse/APPS-3106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPS-3106] Removed special characters from yaml files

- repository/src/main/java/org/alfresco/repo/event2/NodeResourceHelper.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodePropertyFilter.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodeTypeFilter.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapper.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapperFactory.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/ReplaceSensitivePropertyWithTextMapper.java
- repository/src/main/java/org/alfresco/repo/event2/shared/CSVStringToListParser.java
- repository/src/main/java/org/alfresco/repo/event2/shared/QNameMatcher.java
- repository/src/main/java/org/alfresco/repo/event2/shared/TypeDefExpander.java
- repository/src/main/resources/alfresco/events2-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/repo/event2/CSVStringToListParserUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/EventFilterUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/PropertyMapperUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/QNameMatcherUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/TypeDefExpanderUnitTest.java
Backported (cherry-picked) change from this PR: https://github.com/Alfresco/alfresco-community-repo/pull/3147 to release/23.4 branch
> [ACS-9206] Backport MNT-24807 to the `release/23.4` branch

- repository/src/main/java/org/alfresco/repo/event2/NodeResourceHelper.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodePropertyFilter.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodeTypeFilter.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapper.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapperFactory.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/ReplaceSensitivePropertyWithTextMapper.java
- repository/src/main/java/org/alfresco/repo/event2/shared/CSVStringToListParser.java
- repository/src/main/java/org/alfresco/repo/event2/shared/QNameMatcher.java
- repository/src/main/java/org/alfresco/repo/event2/shared/TypeDefExpander.java
- repository/src/main/resources/alfresco/events2-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/repo/event2/CSVStringToListParserUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/EventFilterUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/PropertyMapperUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/QNameMatcherUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/TypeDefExpanderUnitTest.java
Backported (cherry-picked) change from this PR: https://github.com/Alfresco/alfresco-community-repo/pull/3147 to release/23.N branch
> [ACS-9205] Backport MNT-24807 to the release/23.N branch

- repository/src/main/java/org/alfresco/repo/event2/NodeResourceHelper.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodePropertyFilter.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodeTypeFilter.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapper.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapperFactory.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/ReplaceSensitivePropertyWithTextMapper.java
- repository/src/main/java/org/alfresco/repo/event2/shared/CSVStringToListParser.java
- repository/src/main/java/org/alfresco/repo/event2/shared/QNameMatcher.java
- repository/src/main/java/org/alfresco/repo/event2/shared/TypeDefExpander.java
- repository/src/main/resources/alfresco/events2-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/repo/event2/CSVStringToListParserUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/EventFilterUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/PropertyMapperUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/QNameMatcherUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/RepoEvent2UnitSuite.java
- repository/src/test/java/org/alfresco/repo/event2/TypeDefExpanderUnitTest.java
Backported (cherry-picked) change from this PR: https://github.com/Alfresco/alfresco-community-repo/pull/3147 to release/7.4.N branch
> [ACS-9203] Backport MNT-24807 to the release/7.4.N branch

- repository/src/main/java/org/alfresco/repo/event2/NodeResourceHelper.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodePropertyFilter.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodeTypeFilter.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapper.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapperFactory.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/ReplaceSensitivePropertyWithTextMapper.java
- repository/src/main/java/org/alfresco/repo/event2/shared/CSVStringToListParser.java
- repository/src/main/java/org/alfresco/repo/event2/shared/QNameMatcher.java
- repository/src/main/java/org/alfresco/repo/event2/shared/TypeDefExpander.java
- repository/src/main/resources/alfresco/events2-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/repo/event2/CSVStringToListParserUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/EventFilterUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/PropertyMapperUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/QNameMatcherUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/RepoEvent2UnitSuite.java
- repository/src/test/java/org/alfresco/repo/event2/TypeDefExpanderUnitTest.java
Backported (cherry-picked) change from this PR: https://github.com/Alfresco/alfresco-community-repo/pull/3147 to release/7.4.2 branch
> [ACS-9204] Backport MNT-24807 to the release/7.4.2 branch 

- .github/workflows/ci.yml
- .github/workflows/master_release.yml
- repository/src/main/java/org/alfresco/repo/event2/NodeResourceHelper.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodePropertyFilter.java
- repository/src/main/java/org/alfresco/repo/event2/filter/NodeTypeFilter.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapper.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/PropertyMapperFactory.java
- repository/src/main/java/org/alfresco/repo/event2/mapper/ReplaceSensitivePropertyWithTextMapper.java
- repository/src/main/java/org/alfresco/repo/event2/shared/CSVStringToListParser.java
- repository/src/main/java/org/alfresco/repo/event2/shared/QNameMatcher.java
- repository/src/main/java/org/alfresco/repo/event2/shared/TypeDefExpander.java
- repository/src/main/resources/alfresco/events2-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/repo/event2/CSVStringToListParserUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/EventFilterUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/PropertyMapperUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/QNameMatcherUnitTest.java
- repository/src/test/java/org/alfresco/repo/event2/TypeDefExpanderUnitTest.java
Backported (cherry-picked) change from this PR: https://github.com/Alfresco/alfresco-community-repo/pull/3147 to release/23.4 branch
> ACS-9394 Backport MNT-24807 to the `release/23.3` branch

- repository/src/main/java/org/alfresco/repo/workflow/activiti/script/ActivitiScriptBase.java
(cherry picked from commit https://github.com/Alfresco/alfresco-community-repo/commit/ec78a1486c99f1482b13d5c745cf129ab63a3dae)
> [MNT-24938] Added fallback method to obtain deployment category in order to check if workflow is secure (#3236)

- .secrets.baseline
- repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2.java
- repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
- repository/src/test/java/org/alfresco/repo/rendition2/AbstractRenditionIntegrationTest.java
- repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
(cherry picked from commit 74380693d086fc99bd00f128f78e206725bc9780)
> [MNT-24992] Add method to force renditions content hash code (#3288)

- repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
- repository/src/main/java/org/alfresco/repo/event2/EventSender.java
- repository/src/main/java/org/alfresco/repo/event2/EventSenderFactoryBean.java
Backporting https://github.com/Alfresco/alfresco-community-repo/pull/3286
> [MNT-24937] Fix EventTableOutbox messages flooding the logs on bootstrap failure (#3286)

- repository/src/main/java/org/alfresco/repo/rendition2/LocalTransformClient.java
- repository/src/main/resources/alfresco/rendition-services2-context.xml
- repository/src/main/resources/alfresco/repository.properties
Add `local.transform.threadPoolSize=20` for controlling size of thread pool used for transforms.
> [ACS-9490] Use FixedThreadPool for ExecutorService

- repository/src/main/java/org/alfresco/repo/action/executer/AddFeaturesActionExecuter.java
- repository/src/test/java/org/alfresco/repo/action/executer/AddFeaturesActionExecuterTest.java
Skip actionContext to classify as an adhoc property in add-features action logic
> MNT-24891 - Skip actionContext to classify as an adhoc property in add-features action logic

- repository/src/main/java/org/alfresco/repo/action/executer/AddFeaturesActionExecuter.java
- repository/src/test/java/org/alfresco/repo/action/executer/AddFeaturesActionExecuterTest.java
Fix/MNT-24891 backport to 23.3
> Fix/MNT-24891 backport to 23.3

- pom.xml
Bump org.springframework.security:spring-security from 6.3.4 to 6.4.4
> Bump org.springframework.security:spring-security to 6.3.8

- pom.xml
Bump poi-ooxml version to 5.4.0
> Bump poi-ooxml version to 5.4.0

- pom.xml
> Bump spring-security to 6.3.8

- pom.xml
- repository/src/test/resources/testRoutes.xml
Bump camel version from 4.6.0 to 4.11.0
> Bump camel version to 4.11.0

- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/hold/AddToHoldsBulkV1Tests.java
ACS-9578 Changes done as part of test case failure for AddToHoldsBulkV1Tests
> ACS-9578 Changes done as part of test case failure for AddToHoldsBulkV1Tests

- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/CapabilityModel.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/GroupModel.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/RoleModel.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/role/Role.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/role/RoleCollection.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/role/RoleEntry.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/requests/gscore/api/FilePlanAPI.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/base/BaseRMRestTest.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/fileplans/FilePlanTests.java
> [ACS-9399] added few tests.

- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/hold/AddToHoldsBulkV1Tests.java
Cherry picked changes in unstable test from master
(cherry picked from commit 192c1057196ef02b0d619fce1063b8e293cc957b)
> ACS-9652  [Es Connector] Prepare ACS 23.N for release (with ES Connector 5.1.0)

- .secrets.baseline
- pom.xml
- repository/src/main/java/org/alfresco/repo/action/executer/AddFeaturesActionExecuter.java
- repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
- repository/src/main/java/org/alfresco/repo/event2/EventSender.java
- repository/src/main/java/org/alfresco/repo/event2/EventSenderFactoryBean.java
- repository/src/main/java/org/alfresco/repo/rendition2/LocalTransformClient.java
- repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2.java
- repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
- repository/src/main/resources/alfresco/rendition-services2-context.xml
- repository/src/main/resources/alfresco/repository.properties
- repository/src/test/java/org/alfresco/repo/action/executer/AddFeaturesActionExecuterTest.java
- repository/src/test/java/org/alfresco/repo/rendition2/AbstractRenditionIntegrationTest.java
- repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
- repository/src/test/resources/testRoutes.xml
Added commits from 23.3:
- MNT-24992
- ACS-9490
- MNT-24891
Added commits from 23.4:
> ACS-9642 Prepare 23.N forACS-23-5

- amps/ags/rm-community/rm-community-rest-api-explorer/src/main/webapp/definitions/gs-core-api.yaml
This PR is to propose API for exposing AGS Capabilities in the AGS REST API.
> ACS-9428 Add AGS Roles V1 API

- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/action/unzip-to.post.json.js
- repository/src/main/java/org/alfresco/repo/action/executer/ImporterActionExecuter.java
- repository/src/main/java/org/alfresco/repo/model/filefolder/FileFolderServiceImpl.java
- repository/src/main/java/org/alfresco/service/cmr/model/FileExistsException.java
- repository/src/main/java/org/alfresco/service/cmr/model/FolderExistsException.java
- repository/src/test/java/org/alfresco/repo/action/executer/ImporterActionExecuterTest.java
> [ACS-9572]show proper message for duplicate unzipping

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/validator/actions/ActionNodeParameterValidator.java
Return user friendly error message in response to user when a target/destination folder no longer exists while updating folder rules.
> [ACS-9697] Added user-friendly error message.

- packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
- remote-api/src/main/java/org/alfresco/rest/api/impl/validator/actions/ActionNodeParameterValidator.java
return appropriate error message when destination folder does not exist while updating folder rules.
> [ACS-9697] Backport to 23.N

- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/hold/AddToHoldsBulkV1Tests.java
Changes cherry picked from master branch
> ACS-9676 Fix unstable AddToHoldsBulkV1Tests

- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/hold/AddToHoldsBulkV1Tests.java
Changes cherry picked from release/23.N branch
> ACS-9690 Fix unstable AddToHoldsBulkV1Tests

- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/hold/AddToHoldsBulkV1Tests.java
Changes cherry picked from release/23.N branch
> ACS-9689 Fix unstable AddToHoldsBulkV1Tests

- repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessor.java
Backport https://github.com/Alfresco/alfresco-community-repo/pull/3462 changes to 23.N
> MNT-25150 check owner aspect first

- amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/alfresco-global.properties
- amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/rm-service-context.xml
- amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/security/ExtendedSecurityServiceImpl.java
- amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/security/ExtendedSecurityServiceImplUnitTest.java
(cherry picked from commit a3998de1ba2db222cc455061e6a6eeafed9de835)
> MNT-24975 - Repeated IPR groups due to casing inconsistencies (#3459)

- repository/src/main/java/org/alfresco/repo/jscript/Search.java
https://hyland.atlassian.net/browse/ACS-9710 (story)
https://hyland.atlassian.net/browse/ACS-9730 (sub-task)
> [ACS-9710] Test Share with Elasticsearch

- repository/src/main/java/org/alfresco/repo/node/db/DbNodeServiceImpl.java
- repository/src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java
(cherry picked from commit 18016df074d12e99a92b6bed10678c363f9c6867)
> ACS-9923 Removing an aspect needs to invoke onUpdateProperties (#3504)

- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/util/DockerHelper.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/AddRelationshipTests.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java
- amps/share-services/pom.xml
- amps/share-services/src/main/java/org/alfresco/repo/web/scripts/wiki/WikiPageGet.java
- amps/share-services/src/test/java/org/alfresco/repo/web/scripts/wiki/WikiRestApiTest.java
- packaging/distribution/src/main/resources/licenses/notice.txt
- packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/SecondaryTypesTests.java
- pom.xml
- repository/pom.xml
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/authentication/AbstractIdentityServiceAuthenticator.java
https://hyland.atlassian.net/browse/PRODSEC-10577
[com-repo-dependency-tree.log](https://github.com/user-attachments/files/21982604/com-repo-dependency-tree.log)
> [ACS-9933] Use only lang3 3.18

- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/util/DockerHelper.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/AddRelationshipTests.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java
- amps/share-services/pom.xml
- amps/share-services/src/main/java/org/alfresco/repo/web/scripts/wiki/WikiPageGet.java
- amps/share-services/src/test/java/org/alfresco/repo/web/scripts/wiki/WikiRestApiTest.java
- packaging/distribution/src/main/resources/licenses/notice.txt
- packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/SecondaryTypesTests.java
- packaging/tests/tas-restapi/pom.xml
- pom.xml
- repository/pom.xml
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
- repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/authentication/AbstractIdentityServiceAuthenticator.java
https://hyland.atlassian.net/browse/PRODSEC-10564
[com-repo-dependency-tree.log](https://github.com/user-attachments/files/22005057/com-repo-dependency-tree.log)
> [ACS-9933] Use only lang3 3.18 in 23.N

- repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
- repository/src/main/resources/alfresco/repository.properties
- repository/src/main/resources/alfresco/script-services-context.xml
(cherry picked from commit 42324368e57f47f1138e372bc442bc6acdfc8d58)
> [MNT-25242] Add property to control if scope is cleaned (#3520)

- amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/util/DockerHelper.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/AddRelationshipTests.java
- amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java
- amps/share-services/pom.xml
- amps/share-services/src/main/java/org/alfresco/repo/web/scripts/wiki/WikiPageGet.java
- amps/share-services/src/test/java/org/alfresco/repo/web/scripts/wiki/WikiRestApiTest.java
- packaging/distribution/src/main/resources/licenses/notice.txt
- packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/SecondaryTypesTests.java
- pom.xml
- repository/pom.xml
https://hyland.atlassian.net/browse/PRODSEC-10553
[com-repo-dependency-tree.log](https://github.com/user-attachments/files/22043592/com-repo-dependency-tree.log)
> [ACS-9933] Use only lang3 3.18 in 7.4.N

- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/doclist.lib.js
- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/filters.lib.js
MNT-24308 : On click of 'My Favorites' link under 'Documents' in the left panel of 'Document Library' page, all the links appear grayed out
> MNT-24308 : On click of 'My Favorites' link under 'Documents' in the left panel of 'Document Library' page, all the links appear grayed out

- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/forms/pickerresults.lib.ftl
MNT-24776 : Category Picker Error when a User does not have Read Permissions to a Category
> backport MNT-24776 to 23.N

- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/doclist.lib.js
- amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/filters.lib.js
#fixed the query which is compatible for both solar and elastic search 
FYI:
Elasticsearch
https://github.com/user-attachments/assets/8c4f4980-7ad0-41e8-bc26-5d7bbd71167c
Solar search
https://github.com/user-attachments/assets/98bf0899-374b-41d9-87e0-be9751c8381a
https://github.com/user-attachments/assets/3f549d30-7c90-49b0-a5d7-0b5c1cec2152
> MNT-25186: fixed the tags and category filters for elasticsearch

- pom.xml
(cherry picked from commit 96481daae15a040a166e5674d89cdaf50ab64b07)
> [ACS-10155] Bump spring version to 6.2.11 (#3589)

- remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/forms/pickerresults.lib.ftl
MNT-24776 adding if-else conditionals to avoid null values
> MNT-24776 adding if-else conditionals to avoid null values
