data-model/pom.xml
pom.xml
repository/pom.xml

In the current build some packages ("javax.xml" and "org.w3c" for example) are accessible via the JRE System Library AND via other jar files pulled by Maven as transitive dependencies, such as xml-apis.jar. Being on the classpath, they are treated as part of the unnamed module, and the "uniquely visible" constraint is violated.
Please see https://issues.alfresco.com/jira/browse/ACS-544 for full detailed explanation

Changes to poms  to support compatibility with JDK9+ module system

---

.gitignore
repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java
repository/src/test/resources/quick/quick.carryAspectFalse_metadata.json
repository/src/test/resources/quick/quick.carryAspectTrue_metadata.json
repository/src/test/resources/quick/quick.cautious_policy_metadata.json
repository/src/test/resources/quick/quick.eager_policy_metadata.json
repository/src/test/resources/quick/quick.pragmatic_policy_metadata.json
repository/src/test/resources/quick/quick.prudent_policy_metadata.json
repository/src/test/resources/quick/quick.tagging_metadata.json
repository/src/test/resources/quick/quick.tagging_metadata_enable_false.json

Originally https://github.com/Alfresco/alfresco-repository/pull/1055 on the old projects. It was not possible approve and to merge Adina's PR at the time.

REPO-5208 Metadata extract: overwritePolicy, enableStringTagging and carryAspectProperties tests

---

remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
remote-api/src/test/java/org/alfresco/rest/api/tests/util/MultiPartBuilder.java

Add versionState form-data property to POST nodes/{nodeId}/children multipart upload.
Add versionState to MultiPartBuilder.
Add tests for multipart upload

MNT-22036 : REST API always applies versioning

---

repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponent.java
repository/src/test/java/org/alfresco/AppContext05TestSuite.java
repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponentTest.java

The IDS Auth component may fail with other exceptions (e.g. connection error) not just with user authentication, therefore the fix captures those exceptions and re-throw AuthenticationException so other authentication components in the chain can have a go at authenticating the user.

ACS-778: Fixed IDS authentication component.

---

pom.xml
repository/src/main/java/org/alfresco/repo/content/metadata/TikaAutoMetadataExtracter.java

Bump tika to 1.24.1
Remove metadata-extractor dependency
Bump poi to 4.1.2

MNT-22055 : Metadata extraction fails for certain documents

---

core/src/test/java/org/alfresco/util/VersionNumberTest.java
repository/src/main/java/org/alfresco/repo/module/ModuleVersionNumber.java
repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
repository/src/test/java/org/alfresco/repo/module/ModuleVersionNumberTest.java

Now that we create internal releases of the form M.m.r-M9 (milestone), M.m.r-A9 (alpha) and M.m.r-RC9 (release candidate) during development and testing, we need to ensure we can upgrade from any of these to any other, as they may occur in any order and also to the final external release M.m.r. We also will allow a change from the final release back to an internal one for regression testing. The code within ModuleComponentHelper which calls this method, checks if it is the same version (0) and then if it is downgrading (> 0), so if they share the same M.m.r part matches AND is one of these formats, we return <0.

ACS-953 Unable to upgrade from ACS-7.0-M1 or ACS-7.0-M2 to ACS-7.0-A12

---

remote-api/src/test/java/org/alfresco/rest/api/tests/SharedLinkApiTest.java
repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java

In a multi repo node cluster, it is possible one node requests a metadata extract via the ATS and
that another responds to it. In this case the responder needs to recreate the TransformRequest. In
this case the target mimetype was wrong, resulting in the TransformRequest being sent to the wrong
code which then through a NPE because there was no replyQueue specified on the TransformRequest.

ACS-976 Metadata extraction NPE thrown in multi-node cluster using ATS

---

core/src/test/java/org/alfresco/util/testing/category/FrequentlyFailingTests.java
core/src/test/java/org/alfresco/util/testing/category/IntermittentlyFailingTests.java
packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/DeleteTreeTests.java
packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetChildrenTests.java
packaging/tests/tas-integration/src/test/java/org/alfresco/tas/integration/IntegrationFullTests.java
packaging/tests/tas-integration/src/test/java/org/alfresco/tas/integration/IntegrationFullTests1.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/comments/AddCommentsTests.java
remote-api/src/test/java/org/alfresco/repo/web/scripts/invite/InviteServiceTest.java
remote-api/src/test/java/org/alfresco/repo/web/scripts/servlet/RemoteAuthenticatorFactoryAdminConsoleAccessTest.java
remote-api/src/test/java/org/alfresco/repo/webdav/WebDAVMethodTest.java
remote-api/src/test/java/org/alfresco/rest/DeletedNodesTest.java
remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractEnterpriseOpenCMIS11TCKTest.java
remote-api/src/test/java/org/alfresco/rest/api/tests/SharedLinkApiTest.java
repository/src/test/java/org/alfresco/encryption/EncryptionTests.java
repository/src/test/java/org/alfresco/opencmis/CMISTest.java
repository/src/test/java/org/alfresco/opencmis/OpenCmisLocalTest.java
repository/src/test/java/org/alfresco/repo/event2/ChildAssociationRepoEventIT.java
repository/src/test/java/org/alfresco/repo/transfer/NodeCrawlerTest.java

Part of Epic: ACS-959 Fix or suppress the content repository's intermittent test failures

ACS-960 Disable very frequent intermittent test failures

---

pom.xml

This revert is required to allow AGS to build. A reintroduction of this changes will be applied after West drayton

revert of webscripts to version 8.12

---

core/src/main/java/org/alfresco/util/transaction/SpringAwareUserTransaction.java
pom.xml
remote-api/src/test/java/org/alfresco/repo/web/scripts/quickshare/QuickShareRestApiTest.java
repository/src/test/java/org/alfresco/repo/transaction/TransactionServiceImplTest.java

- Update rest api test as per https://github.com/spring-projects/spring-framework/commit/5de549d7d4324c7e30ac607e15ebac444f8c3f28
- prior to spring 5.3.0, AbstractFallbackSQLExceptionTranslator was returning UncategorizedSQLException (wrapping the initial one) when not able to identify an exception - now it returns null (https://github.com/spring-projects/spring-framework/commit/e9cded560d6ecb73aa5bfca57e06b09fa0013294#diff-c6aa1c6a4b11e8a722808e945c4c5b6ef471c42871c7ce830554dde81ad7f2c2L89)

ACS-1033 : Spring upgrade to 5.3.2

---

repository/src/main/java/org/alfresco/repo/content/metadata/AbstractMappingMetadataExtracter.java
repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java
repository/src/test/java/org/alfresco/repo/action/executer/ContentMetadataEmbedderTest.java

Bug found while reviewing documents on how to create a custom metadata extractor. The original refactor had left the repo doing the mapping. It should have been passing the fully qualified repo properties to the T-Engine to do the mapping.
Linked to:
* https://github.com/Alfresco/acs-packaging/pull/1826
* https://github.com/Alfresco/alfresco-transform-core/pull/316

REPO-5191 Bug: T-Engine should provide mapping rather than the repo.

---

repository/src/main/java/org/alfresco/repo/virtual/ref/ZeroReferenceParser.java
repository/src/test/java/org/alfresco/repo/virtual/store/VirtualStoreImplTest.java

Copy of https://github.com/Alfresco/alfresco-repository/pull/1263

Fix MNT-21968 catch NumberFormatException on parseInt

---

core/pom.xml
data-model/pom.xml
packaging/tests/tas-integration/pom.xml
packaging/tests/tas-restapi/pom.xml
packaging/war/pom.xml
pom.xml
remote-api/pom.xml
remote-api/src/main/java/org/alfresco/repo/webdav/WebDAVServlet.java
repository/pom.xml

- group jakarta dependencies in the POMs
- define explicit version properties for the various jakarta APIs
- replace all *javax* libraries with their *jakarta* equivalent
- exclude all *javax* libraries brought in by our dependencies (they can't be handled through _dependencyManagement_ due to the different jar names)
- upgrade the *jakarta* libraries to the latest versions that still use the _javax_ package namespace

ACS-1146 Replace *javax* dependencies with *jakarta* libraries

---

core/src/main/java/org/alfresco/query/AbstractCannedQuery.java
repository/src/main/java/org/alfresco/repo/node/archive/GetArchivedNodesCannedQuery.java
repository/src/main/java/org/alfresco/repo/node/archive/GetArchivedNodesCannedQueryParams.java
repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/query-archived-nodes-common-SqlMap.xml

GetArchivedNodesCannedQuery now will return only the required results (page) based on offset(skipCount) and limit(maxItems).
Offset and limit are set as rowBounds for mybatis.
Added count query for GetArchivedNodesCannedQuery in order to preserve the totalItems.
Because GetArchivedNodesCannedQuery returns only the required results, an extra condition was added to establish `hasMoreItems`

MNT-20775 : deleted-nodes with maxitems parameter take longer

---

repository/src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceFactory.java
repository/src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceImpl.java
repository/src/main/resources/alfresco/opencmis-context.xml
repository/src/main/resources/alfresco/repository.properties

- add new configurable option to request set of renditions when uploading via CMIS (none by default)
- note: in the (unlikely) event a customer *relied* on previous behaviour (rather than dynamic requests) they can override & set to "doclib"

MNT-14308: CMIS - optionally request rendition(s) when uploading docs

---

repository/src/test/java/org/alfresco/repo/security/authority/AuthorityServiceTest.java

Created unit test testIfGroupIsAdminAuthority to check if public method isAdminAuthority correctly validates groups:
* Verify it can identify GROUP_ALFRESCO_ADMINISTRATORS as an admin group
* Verify created groups (non administrators) and users are not considered administrators
* Add a subgroup to the parent group and verify if its still identified as non admin
* Add the group to the administrators group and verify if both group and subgroup are identified correctly as admins
* Add the user to the subgroup and verify if he's an admin
* Create a group with the same name as an admin user, group should not be identified as admin

MNT-22135 Filter policy to only run on admin auth - Unit test

---

repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorPermissionsTest.java

Changes have been made to support then node ownership evaluation happening on [enterprise](https://github.com/Alfresco/alfresco-enterprise-repo/pull/244).

[REPO-5568] Owner permissions not evaluated in enterprise code

---

repository/src/test/java/org/alfresco/repo/security/authority/AuthorityServiceTest.java

Created unit test testIfGroupIsAdminAuthority to check if public method isAdminAuthority correctly validates groups:
* Verify it can identify GROUP_ALFRESCO_ADMINISTRATORS as an admin group
* Verify created groups (non administrators) and users are not considered administrators
* Add a subgroup to the parent group and verify if its still identified as non admin
* Add the group to the administrators group and verify if both group and subgroup are identified correctly as admins
* Add the user to the subgroup and verify if he's an admin
* Create a group with the same name as an admin user, group should not be identified as admin
(cherry picked from commit 592dde531f3516a8fe3091864584c04465a86cbf)

MNT-22135 Filter policy to only run on admin auth - Unit test (#275)

---

remote-api/src/main/resources/alfresco/public-rest-context.xml
repository/src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceFactory.java

- note: PublicApiAlfrescoCmisServiceFactory extends AlfrescoCmisServiceFactory and overrides getCmisServiceTarget
- hence, also ensure property (cmis.create.doc.request.renditions.set) is set for public rest api spring context
- note: set following log4j.properties: log4j.logger.org.alfresco.opencmis=info

MNT-14308: CMIS - optionally request rendition(s) when uploading docs - part 2

---

repository/src/main/java/org/alfresco/repo/rendition2/TransformationOptionsConverter.java
repository/src/test/java/org/alfresco/repo/rendition2/TransformationOptionsConverterTest.java

The TransformationOptionsConverter class did not convert the newer transform option format a Map<String, String> to the legacy ImageTransformationOptions class that contains the commandOption (OPT_COMMAND_OPTIONS) property. As a result no legacy transformer is asked if it can do the transform.
There are no Legacy transformers in ACS 7, so this fix cannot be applied there as the class has been removed. Fixing on 6.2.N.

MNT-21694 500 error on new logo upload with Legacy transforms

---

packaging/tests/environment/docker-compose-minimal+transforms.yml
packaging/tests/environment/docker-compose-minimal.yml
pom.xml
repository/pom.xml
repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging-context.xml
repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging.properties

- enable camel JMX management
- add `camel-management` dependency
- disable JMS connection-pool warm-up
- update ActiveMQ URLs to force clients to connect through the `java.nio` APIs

ACS-1253 Enable Camel JMX management

---

pom.xml

Upgraded TAS restapi to fix SyncServiceAPITests failing test in acs-packaging (Sync Service TAS tests).

Upgrade TAS restapi

---

repository/src/main/java/org/alfresco/repo/forms/processor/node/ContentModelFormProcessor.java

- Fix the name property persistence in ContentModelFormProcessor to only save when the property value is actually changed. This prevents the FilenameFilteringInterceptor to be called when there are no changes to the file name.

ACS-1201: Model integrity violation saving properties

---

repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
repository/src/main/resources/alfresco/public-services-security-context.xml
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java

- On move node, verify if parent has pending acl aspect applied and consider the pending shared ACL to update inheritance to avoid ending up with mixed permissions as children of pending acl nodes do not have the correct acls and when moved, keep their wrong acl.
- Add public method setInheritanceForChildren that receives an additional param: forceSharedACL. If an unexpected ACL occurs in a child, it can be overridden by setting it.
- Implement method setInheritanceForChildren that receives an additional parameter: forceSharedACL
- Add method setFixedAcls that receives an additional parameter: forceSharedACL - When a child node has an unexpected ACL, setting this parameter to true will force it to assume the new shared ACL instead of throwing a concurrency exception. When the shared ACL …

MNT-21898 Unexpected ACLs when job runs Fix

---

repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java

Fix:
*Changed method setFixedAcls on class ADMAccessControlListDAO to continue to propagate through children to apply the correct acl not only when the current child acl matches the shared acl to replace but also when the current child acl matches the new shared acl
Unit Test:
*Refactored the unit test FixedAclUpdaterTest to be able to add in a new test without repeating code: separating the operations that set the permissions from the one that triggers the job into separate methods
*As it was if one test failed, leaving aspects to be processed, the test would run indefinitely (it was programmed to keep running the job while there where nodes with the aspect). Added a verification to stop triggering the job if the number of nodes with the pendingFixAcl did not change between executions. …

[MNT-21847] - Aync permissions fail when new nodes are created (#1188)

---

repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java

* MNT-22040 - Copying nodes that contain sys:pendingFixAcl aspect
* Increased coverage of unit tests
* Added public method removePendingAclAspect
* Changed the job to use the removePendingAclAspect method instead of
repeating the same set of operations twice
* Changed method setFixedAcls to use sharedAclToReplace property of node
if it has the pendingFixAcl aspect applied instead of using the current
shared ACL to be replaced
* Added more tests and validations
* Fixed cuncurrency issues when updating parent and child at the same time, permissions triggered by a move on a node with a pending acl and permissions needeing to be reapplied on nodes that already have the pending acl aspect
* Increase the tree strcuture as sometimes we don't reach the timeout in tests
* code cleanup and …

MNT-22040 Copying nodes that contain sys:pendingFixAcl aspect (#188)

---

repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
repository/src/main/resources/alfresco/public-services-security-context.xml
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java

* On move node, verify if parent has pending acl aspect applied and consider the pending shared ACL to update inheritance to avoid ending up with mixed permissions as children of pending acl nodes do not have the correct acls and when moved, keep their wrong acl.
* Add public method setInheritanceForChildren that receives an additional param: forceSharedACL. If an unexpected ACL occurs in a child, it can be overridden by setting it.
* Implement method setInheritanceForChildren that receives an additional parameter: forceSharedACL
* Add method setFixedAcls that receives an additional parameter: forceSharedACL - When a child node has an unexpected ACL, setting this parameter to true will force it to assume the new shared ACL instead of throwing a concurrency exception. When the shared ACL …

MNT-21898 Unexpected ACLs when job runs Fix (#344)

---

repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
repository/src/main/resources/alfresco/events2-context.xml
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java

In order to not suffer from a drop in performance caused by the introduction of the new events system, the sendEvent calls (and related code) are now executed asynchronously using a thread pool.
The pool is controlled by these properties:
repo.event2.threadPool.priority=1
repo.event2.threadPool.coreSize=8
repo.event2.threadPool.maximumSize=10

[ACS-1291] Asynchronous mechanism to send events

---

repository/src/main/java/org/alfresco/ibatis/IdsEntity.java
repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml

* Added method selectNodesWithAspects that accepts a boolean as param to order values
* Added param ordered to IdsEntity class
* Added optional ordered param to the query template that orders the results by node id in asc order
* Added method getNodesWithAspects that accepts a boolean as param to order values in nodeDAO
* FixedACLUpdater Job calls the new getNodesWithAspects, with the ordered param as true

MNT-22295 - FixedACLJob not processing all nodes due to unordered results

---

repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterListener.java
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterUnitTest.java

Change default for user filter to empty, as changes from all users could affect metadata
or permissions which might need to be indexing by the enterprise Elasticsearch Connector.

SEARCH-2768 Add callback feature for asynchronous ACL updates.

---

repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
repository/src/main/resources/alfresco/events2-context.xml
repository/src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java

This reverts commit 28f1429a, PR #371

Revert "SEARCH-2782 use current transaction timestamp instead of current time as event time"

---

repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
repository/src/main/java/org/alfresco/repo/event2/EventGeneratorQueue.java
repository/src/main/resources/alfresco/events2-context.xml
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
repository/src/test/java/org/alfresco/repo/event2/EventGeneratorQueueUnitTest.java
repository/src/test/java/org/alfresco/repo/event2/EventGeneratorTest.java
repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
repository/src/test/java/org/alfresco/repo/event2/RepoEvent2UnitSuite.java

Original issue was ACS-1291, however the original commit for this on master was reverted and then later included in REPO-5610
REPO-5610 events are not actually sent to activemq (#360)
* Add events tests
* Polished put test: connects to JMS via TCP and validate that the event sent is also received back
* Now the tests provides a simple main() that listens on the topic, useful for quick debug sessions
* Now the user name is collected in the calling thread, so that the sendEvent does not silently fails
* Apply changes following review
* Now using queue system to guarantee events order
* Add license
* Updated logs and corrected comments
* Remove empty methods
* Now catering for spurious events at startup when database is bootstrapped
* Now preserving the txn-id in all events
* Moved up …

MNT-22300/MNT-22301 Performance of property update in 7.0.0

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/RenditionVersionTests.java
pom.xml

Added TAS test for rendition version REST API. The tests are executed as part of "REST API TAS tests part3"  tas tests. See tests/tas-restapi/src/test/resources/test-suites/part3-suite.xml.
https://alfresco.atlassian.net/browse/ACS-276

ACS-276 tas test for rendition version

---

repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
repository/src/main/java/org/alfresco/repo/domain/permissions/AclDAO.java
repository/src/main/java/org/alfresco/repo/domain/permissions/AclDAOImpl.java
repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
repository/src/main/resources/alfresco/events2-context.xml
repository/src/test/java/org/alfresco/repo/domain/node/NodeDAOTest.java
repository/src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
repository/src/test/java/org/alfresco/repo/security/permissions/impl/AclDaoComponentTest.java

This PR is updated because we face an issue when the transaction entry object is not initialized and we cannot retrieve the commit time. This happens when no nodes were added to the transaction because there aren't changes to any node, but we need to produce some events (e.g. permission update).
Before I’m getting the commit time using the nodeDao:
```
Long currentTransactionId = nodeDAO.getCurrentTransactionId(true);
Transaction transaction = nodeDAO.getTxnById(currentTransactionId);
Instant commitTimeMs = Instant.ofEpochMilli(transaction.getCommitTimeMs());
```
The PermissionService does not invoke always NodeDAOImpl.getCurrentTransaction() method, so even if we are inside a transaction the Transaction entry will not be initialized and the method nodeDAO.getCurrentTransactionId() will …

SEARCH-2782 commit time as event time

---

pom.xml

Dependabot is failing because of a weird issue, I guess from their side, so I created the bump PR manually:
```
fetcher | ERROR <job_77448412> Error during file fetching; aborting
fetcher | ERROR <job_77448412> key not found: :security_updates_only
```

SEARCH-2748 Bump restapi from 1.57 to 1.58

---

packaging/war/src/main/webapp/error.jsp
packaging/war/src/main/webapp/index.jsp

https://alfresco.atlassian.net/browse/MNT-22183
Relative URLs can be dangerous since browser may not determine the correct directory. If the HTML uses path-relative CSS links, it may be susceptible to path- relative stylesheet import (PRSSI) vulnerabilities. This could allow an attacker to take advantage of CSS imports with relative URLs by overwriting their target file.

[MNT-22183] Use absolute paths for stylesheets

---

packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CancelCheckOutTests.java
packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CheckInTests.java
packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CheckOutTests.java
packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CreateDocumentTests.java
packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/IsPrivateWorkingCopyTests.java
pom.xml

- upgrade tas-cmis (see fix in https://github.com/Alfresco/alfresco-tas-cmis/pull/56)
- remove `bug-ws-REPO-5391` flag on checkout tests

REPO-5391 : [cmis webservices] isPrivateWorkingCopy throws NullPointerException

---

remote-api/src/test/java/org/alfresco/rest/api/tests/TestPeople.java

The related test was inherently flaky,  sometimes passing, sometimes not. This was due to the way the test was structured: it was ordering by a Person first name but two person with the same first name ("Alice") were present in the dataset used by the test.
The underlying sorting algorithm does not take in account other fields:
`        params.put("orderBy", sortColumn + " " + (asc ? "ASC" : "DESC"));
`
For that reason, I had to change the text expectations so that only the first name is taking into consideration. Changes to the dataset would have influenced other unrelated tests.

REPO-5630 Fix for intermittent failing test PeopleTest.testPagingAndSortingByFirstNameDesc

---

repository/src/main/java/org/alfresco/repo/invitation/InvitationServiceImpl.java
repository/src/main/java/org/alfresco/repo/invitation/site/InviteNominatedSender.java

Fixed the first approach. No longer catching the Exception and instead preventing to invoke the email action if the invited user does not have an email address

ACS-895 User email should not be necessary for joining a site

---

pom.xml

Include fix for ATS-730 this will fix the selection of transformer based on priority.

MNT-22425 : bump transform.model to 1.0.2.10

---

repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java

As a result of the fixedACL job finish off right before a few assertions take place, some tests that call `FixedAclUpdaterTest::getFirstNodeWithAclPending(QName nodeType, NodeRef parentRef)` occasionally fail as a sought after node with the `ASPECT_PENDING_FIX_ACL` aspect and grandchildren nodes is not always found after setting new permissions on the test data (a set of subfolders and files). An increase of the test data solves this issue.

REPO-5632 Investigate intermittent failing tests in AppContext05TestSuite

---

repository/src/main/java/org/alfresco/repo/domain/schema/SchemaBootstrap.java
repository/src/main/java/org/alfresco/util/schemacomp/Difference.java
repository/src/main/java/org/alfresco/util/schemacomp/RedundantDbObject.java
repository/src/main/java/org/alfresco/util/schemacomp/Result.java
repository/src/main/java/org/alfresco/util/schemacomp/SchemaDifferenceHelper.java
repository/src/main/java/org/alfresco/util/schemacomp/ValidationResult.java
repository/src/test/java/org/alfresco/util/schemacomp/SchemaBootstrapTest.java
repository/src/test/java/org/alfresco/util/schemacomp/SchemaDifferenceHelperUnitTest.java

Changes made to support other `Result` implementations when detecting optional patches problems descriptions.

REPO-5631 Investigate different types of results for optional patches difference detection

---

pom.xml

REPO-5234: Metadata extraction fails for Embedded files

---

amps/ags/rm-community/rm-community-repo/unit-test/resources/rest/schema.json

This prevents the unit tests from failing when the webpage is unavailable. It has the side
effect of not picking up any updates to the schema.

RM-7171 Remove reference to http://swagger.io/v2/schema.json to avoid downloading schema.

---

amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/node-browser/node-browser.get.json.ftl
remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/support-tools/admin-nodebrowser.get.html.ftl

In node browser:
- Added macro convertToJSON to recursively parse hashes and enumerables
- Added attempt/recover in macros to handle errors and not break the page
- Changed the output of serialized objects to JSON format
In both admin console and node browser:
- Adjusted consistency of the output between both pages when an error occurs
- Validate the depth of each hash. When we find a hash with over 1000 elements, we throw an error instead of displaying the object. Used the stop tag to effectively force an abort of the template processing preventing performance or security issues regarding very large objects.
Related PRs:
- Original PR in repo that fixes the serialised objects: https://github.com/Alfresco/alfresco-community-repo/pull/291
- Original PR in share (when share-services was …

MNT-20500 - Admin console breaks with serialised objects

---

repository/src/main/java/org/alfresco/repo/usage/RepoUsageComponentImpl.java
repository/src/main/java/org/alfresco/util/DateUtil.java
repository/src/test/java/org/alfresco/repo/usage/RepoUsageComponentTest.java

* Original problem is that the remaining time to license expires is calculated in days (long, not double) and anything less then 24h computes to 0 days. The validation for license being valid is that the remaining days is more than zero.
* Added method calculateMs in DateUtil class to return the interval in ms considering 2 given dates and respective timezones
* Changed the validation to use the remaining milliseconds value instead of remaining days
* Added unit test where license expires 6 hours from now - repo is not supposed to enter read-only mode
* Added unit test where license expired 1 minute ago - repo is supposed to enter read-only mode

MNT-21837 License expires 23h earlier 

---

repository/src/main/java/org/alfresco/repo/usage/RepoUsageComponentImpl.java
repository/src/main/java/org/alfresco/util/DateUtil.java
repository/src/test/java/org/alfresco/repo/usage/RepoUsageComponentTest.java

* MNT-21837 - License expires 23h earlier
* Original problem is that the remaining time to license expires is calculated in days (long, not double) and anything less then 24h computes to 0 days. The validation for license being valid is that the remaining days is more than zero.
* Added method calculateMs in DateUtil class to return the interval in ms considering 2 given dates and respective timezones
* Changed the validation to use the remaining milliseconds value instead of remaining days
* Added unit test where license expires 6 hours from now - repo is not supposed to enter read-only mode
* Added unit test where license expired 1 minute ago - repo is supposed to enter read-only mode
(cherry picked from commit 630cd99067bc7f8d4137431c434e5e51f64460fd)

MNT-21837 License expires 23h earlier  (#541)

---

repository/src/main/java/org/alfresco/repo/usage/RepoUsageComponentImpl.java
repository/src/main/java/org/alfresco/util/DateUtil.java
repository/src/test/java/org/alfresco/repo/usage/RepoUsageComponentTest.java

* period.getMillis() (joda lib) returns an int instead of a long, so on larger periods (like 30days) we get an error that the value cannot fit in an int
* Changed the validation to only calculate the remaining milliseconds in the edge case of the remaining days being zero (as both 23h before and 23h after correspond to 0 remaining days)
* Added a unit test that validates the usage 60 days up from the licence expiring to validate the problem stops occurring
* Added a unit test that validates the usage 30 days after the licence expiring to cover all use cases

 MNT-21837 - License expires 23h earlier - correction

---

repository/src/main/java/org/alfresco/repo/usage/RepoUsageComponentImpl.java
repository/src/main/java/org/alfresco/util/DateUtil.java
repository/src/test/java/org/alfresco/repo/usage/RepoUsageComponentTest.java

* period.getMillis() (joda lib) returns an int instead of a long, so on larger periods (like 30days) we get an error that the value cannot fit in an int
* Changed the validation to only calculate the remaining milliseconds in the edge case of the remaining days being zero (as both 23h before and 23h after correspond to 0 remaining days)
* Added a unit test that validates the usage 60 days up from the licence expiring to validate the problem stops occurring
Added a unit test that validates the usage 30 days after the licence expiring to cover all use cases
(cherry picked from commit 6e1d25a8f082171ccf65e393554ccf8a8c2dfc8e)

 MNT-21837 - License expires 23h earlier - correction (#544)

---

repository/src/main/resources/alfresco/transforms/0100-basePipelines.json

Removed HTML pipelines that use LibreOffice in order to prevent BSSRF attacks. New pipelines have been added so the transformations can be performed via TXT.
A PR has also been raised in alfresco-transform-service: https://github.com/Alfresco/alfresco-transform-service/pull/412
DOCS-6236 has been created containing a document that describes how to remove the LO pipelines on current installations and also how to restore them.
See also: https://github.com/Alfresco/alfresco-transform-service/pull/412 (enterprise / private repo)

[MNT-21611] Removed HTML transformation pipelines (with LibreOffice). Added new HTML pipelines via TEXT.

---

remote-api/src/main/java/org/alfresco/repo/web/scripts/RepositoryContainer.java

- Changed deleteTempFileOnClose

APPS-986: [AGS] Export of records with size> 4 MB fails

---

repository/src/main/resources/alfresco/transforms/0100-basePipelines.json

`transformerFailover` requires two transformers. As one of the two used by `libreofficeToPdf` was removed, the `transformerFailover` also needed to be removed.

ACS-1734 Remove broken transformerFailover from libreofficeToPdf

---

repository/src/main/resources/alfresco/transforms/0100-basePipelines.json

Follow on from #572.
Removed broken transformer `libreofficeToPdf`
Populate the source & target for the `libreofficeToPdfBoxViaPdf` transformer.
We take the each `libreofficeToPdf` Source and combine with `pdfbox` application/pdf Targets.

ACS-1734 Remove libreofficeToPdf + libreofficeToPdfBoxViaPdf

---

repository/src/main/resources/alfresco/transforms/0100-basePipelines.json

This PR has been raised to ensure both master, 7.0.N and 6.2.N have the same 0100-basePipelines.json files as they all use the same versions of T-Engines.

[ACS-1776] Add missing pipeline outlookMsgToLibreofficeViaText

---

amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/script/CustomPropertyDefinitionPost.java

* Upgrading org.json:json from version 20090211 to 20201115 introduced the issue as getString method in the newer version does not allow for values other than strings
* Replaced getString for the get method

MNT-22481 - Unable to Create Custom Metadata

---

repository/src/main/resources/alfresco/scheduled-jobs-context.xml
repository/src/main/resources/alfresco/subsystems/Search/solr6/solr-backup-context.xml

- Add friendly name to scheduled jobs that are currently showing class names

MNT-21534: Alfresco does not pull correct name for several scheduled jobs

---

core/pom.xml

Removed dom4j:dom4j:1.6.1 dependency as org.dom4j:dom4j:2.1.1 is being brought in by surf-webscripts

[REPO-4514] Removed dom4j dependency

---

packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CancelCheckOutTests.java
pom.xml

This feature is working when tested against a standard environment, but not when tested against an environment with AGS on top of it. 
Hence, to be able to run the test suite in both the standard community pipeline and in the enterprise, AGS-powered Single-Pipeline, and have both green (while the bug, if any, gets analyzed and eventually fixed), I've created a new marker for problems like this.
It will then be used by the Single PIpeline to exclude these tests only there and will save us the need to use a temporary `@BUG` annotation that would exclude the test for good even from here, where it works and where we want to continue to run it.

ACS-1742 - Marked test as NOT_SUPPORTED_ON_SINGLE_PIPELINE

---

pom.xml

(cherry picked from commit 3530e3dc3b9ac13c1bfd40360a318e58b4695bfd)

[PRODSEC-5254] Bump commons-compress to 1.21 (#658)

---

amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/base/BaseRMRestTest.java
amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/capability/RMAfterInvocationProvider.java

* Change isUnfiltered to protected so we can extend it in enterprise
* Added test method to be able to do a cmis query test
Original commit in governance-services: https://github.com/Alfresco/governance-services/commit/e4e3235328543439c9fce5a778b0c3474071ec14

MNT-22600 Nodes with security marks appear unfiltered on CMIS DB queries

---

remote-api/src/main/java/org/alfresco/opencmis/CMISServletDispatcher.java
remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/JsonpCallbackNotAllowedException.java
remote-api/src/main/resources/alfresco/messages/rest-framework-messages.properties
remote-api/src/main/resources/alfresco/public-rest-context.xml
remote-api/src/test/java/org/alfresco/rest/api/tests/TestCMIS.java
repository/src/main/resources/alfresco/repository.properties

* MNT-22428: configurable unsecure jsonp callback CMIS operation
(cherry picked from commit 5807e756bdd8758303d2a3894c87b07990d50a17)

MNT-22428: configurable unsecure jsonp callback CMIS operation (#698)

---

remote-api/src/main/resources/alfresco/public-rest-context.xml

- note: sanity checked in local dev context (went from 503 to 200 success) ...
- fix needed to unblock ACS-2063 (for epic ACS-118)

ACS-2067: Fix probes when DAU (Direct Access Url) support is enabled

---

repository/src/main/java/org/alfresco/repo/admin/patch/impl/SurfConfigFolderPatch.java
repository/src/main/java/org/alfresco/repo/batch/BatchProcessor.java

Added the missing implementations for BatchWorkerProvider methods which was added as part of https://alfresco.atlassian.net/browse/ACS-1112.
This was causing the Repo Directory management admin page to stop working as described here. https://alfresco.atlassian.net/browse/ACS-2238

ACS-2238 Added missing BatchProcessWorkProvider implementations

---

data-model/src/main/java/org/alfresco/service/cmr/repository/ArchivedIOException.java
remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/ApiException.java
remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/ArchivedContentException.java
remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/ArchivedIOException.java
remote-api/src/main/java/org/alfresco/rest/framework/webscripts/AbstractResourceWebScript.java
remote-api/src/main/resources/alfresco/public-rest-context.xml
repository/src/main/java/org/alfresco/repo/content/AbstractContentReader.java

Adds a Precondition Failed (412) error response when attempting the get content that is Archived.
Discovered a bug:
When an error is thrown while attempting to access content the Content-Length header is set but no content is returned (obviously we've had a error so there shouldn't be any 😄). This causes requesting clients to hang until they timeout, as they are expecting content to be there when none will be returned.

ACS-2222 Add ArchivedIOException

---

repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
repository/src/test/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistryTest.java
repository/src/test/java/org/alfresco/repo/content/transform/TransformerConfigTestSuite.java

* T-Engines config need to be combined in the same predefined order in the all-in-one transformer,
T-Router and the Content Repository with individual T-Engines.

ACS-2270 Read T-Engine config in alphabetical order

---

repository/src/main/java/org/alfresco/repo/content/AbstractContentReader.java

The getContentString() method catches all Exceptions and re-throws as a
custom ContentIOException. We want ArchivedIOExceptions re-thrown.
Supersedes #811

ACS-222 Add missing ArchivedIOException throw

---

packaging/tests/tas-webdav/src/test/java/org/alfresco/webdav/UnlockFileTests.java
packaging/war/src/main/webapp/error.jsp

- appears to be regression from REPO-3275 (due to apparent copy & paste from index.jsp)
- added new -ve test added to TAS WebDAV to repeat this specific issue (without fix - fails with 302 instead of 404)
- see also [WebDavUtil.isLocked()](https://github.com/Alfresco/alfresco-tas-webdav/blob/master/src/main/java/org/alfresco/webdav/dsl/WebDavUtil.java#L359-L376)

MNT-22136: WebDAV PROPFIND returns 302 instead of 404 (for docker image only)

---

pom.xml
remote-api/src/main/java/org/alfresco/rest/api/ContentStorageInformation.java
remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
remote-api/src/main/java/org/alfresco/rest/api/model/ContentStorageInfo.java
remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeStorageInfoRelation.java
remote-api/src/main/resources/alfresco/public-rest-context.xml
remote-api/src/test/java/org/alfresco/rest/api/impl/ContentStorageInformationImplTest.java

This PR is still work in progress.
All below changes are annotated `@Experimental` as they are subject to change.
- Added `NodeStorageInfoRelation` to handle REST request for get StorageProps 
- Added `ContentStorageInfo` model class to expose StorageProps iin REST response
- Added `ContentStorageInformation` interface and its implementation (along with unit test) as a proxy to get StorageProps

ACS-2151 Get StorageProps endpoint

---

remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java

-  Added  new methods to use propQName instead of PROP_CONTENT to be consistent with the rest of the project. 
-  Also added their corresponding tests.
-  Deprecated methods that use PROP_CONTENT

ACS-2216: Fix incorrect ContentService Java Interface - should accept content propQName

---

remote-api/src/main/java/org/alfresco/opencmis/CMISServletDispatcher.java
remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
remote-api/src/main/resources/alfresco/public-rest-context.xml
repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
repository/src/main/resources/alfresco/content-services-context.xml
repository/src/main/resources/alfresco/repository.properties

- moved existing pre-configured allow list from remote-api to repository layer ("nodes.nonAttachContentTypes" xml -> "content.nonAttach.mimetypes" prop)
- now also used by DAU (as well as existing V1 REST API and CMIS to get/download content)

PRODESC-5780: ACS Repo DAU APIs to also use non-attach allow list

---

data-model/pom.xml
data-model/src/main/java/org/alfresco/repo/content/MimetypeMap.java
data-model/src/test/java/org/alfresco/repo/dictionary/DiffModelTest.java
pom.xml
remote-api/pom.xml
repository/pom.xml
repository/src/main/java/org/alfresco/repo/remoteconnector/RemoteConnectorResponseImpl.java
repository/src/main/resources/alfresco/tika/tika-config.xml

1. Tika 2.x (parsers to be precise) doesn't bring the same transitive dependencies as Tika 1.x
* Explicitly included needed dependencies for projects depending on transitive ones.
* Removed excludes which are no longer needed.
2. New configuration option `loadErrorHandler` not possible to set to `IGNORE` the only option which allows us to run in case of misconfigured classpath) is to set it to `WARN`.
Tika 2.1.0 still depend on the POI 4.1.2 so we shouldn't upgrade it.

ATS-969 Upgrade tika (not poi)

---

data-model/src/main/java/org/alfresco/repo/content/ContentRestoreParams.java
data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
repository/src/main/java/org/alfresco/repo/content/AbstractRoutingContentStore.java
repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
repository/src/main/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStore.java
repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
repository/src/main/resources/alfresco/public-services-security-context.xml
repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreUnitTest.java

- Added new methods in `ContentStore`, `ContentService` and implementations.
- Added unit tests for most implementations.
- Refactored some `ContentStore` implementation due to common code used for existing and newly added methods.
- Moved storage properties related unit tests from `AggregatingContentStoreTest` (which looks to be in "never-run" suite) to newly created `AggregatingContentStoreUnitTest`

ACS-2200: Java API for archive/archive-restore content

---

amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/version/RecordableVersionServiceImpl.java
repository/src/main/java/org/alfresco/repo/version/Version2ServiceImpl.java
repository/src/main/resources/alfresco/core-services-context.xml
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java

* Added configuration to use child association index on version creation - disabled by default
* Added unit test to verify both cenarios
* Included configuraion in [ags]

MNT-22715 - Setting Version Child Assoc Index Configurable

---

repository/src/main/java/org/alfresco/repo/version/Version2ServiceImpl.java
repository/src/main/resources/alfresco/core-services-context.xml
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java

* Set association index on new version creation
* Unit test to verify the child assoc index is set on versions
(cherry picked from commit c9e98b4)
* Added configuration to use child association index on version creation - disabled by default
* Added unit test to verify both cenarios
(cherry picked from commit d729443)

MNT-22715 - Document Version Issue

---

remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java

Replaced org.springframework.extensions.surf.util.URLEncoder with the java.net.URLEncoder for encoding filenames containing characters like ")" and "(" in the content-disposition response header.

MNT-22668: missing encoded characters for some characters like ‘(’ and ‘)’

---

remote-api/src/main/java/org/alfresco/repo/web/scripts/RepositoryContainer.java

To minimize log pollution, full stack trace of ArchivedIOException (content is archived) will be logged only when debug enabled. 
Exception is re-thrown as WebscriptException with error code 412 to allow similar handling in surf-webscripts (see [PR#135](https://github.com/Alfresco/surf-webscripts/pull/135))

ACS-2334 improve ArchivedIOException logging

---

pom.xml

Added netty-codec-http version 4.1.71.Final to fix vulnerability nested in camel-amqp dependency.

Content-services - Veracode Scan Detected Vulnerabilities in Component Netty/Codec in Application ACS_EXT_MASTER

---

pom.xml

(cherry picked from commit cc11c13e548804a8b52ac931f96440af1add5c44)

MNT-22563: bumped jdom2 version to 2.0.6.1 (#885)

---

pom.xml

Due to dependency conflicts (in Azure Connector AMP) and vulnerabilities apache.camel and netty-codec-http dependency versions have to be changed. 
This PR is mostly dealing with netty.io related version bumps (due to vulnerability found in netty-codec-http library). 
Community-repo is providing these libraries in AMPs and there (combined with AMP specific dependencies) a dependency conflict is very likely to happen.
A follow up PR will be created in Azure Connector AMP project to properly handle provided dependencies and exclude conflicting Azure libraries.

ACS-2104: Changing apache.camel and netty-codec-http dependency versions

---

.github/dependabot.yml

- we're now at Camel 3.7.7 ( hence remove Camel exclusion of > 3.7.1 )
- to enable future suggestions, eg. should prompt with 3.7.7 to 3.14.0 (or maybe 3.14.1)
- also logged ACS-2476 (in case of compile-time/run-time incompatibilities and aligning with Netty)

ACS-2104: Remove Camel exclusion from DependABot

---

scripts/travis/trigger_travis.sh

…EMP to trigger downstream project builds
(cherry picked from commit aeea303)

Should be using TRAVIS_ACCESS_TOKEN rather than TRAVIS_ACCESS_TOKEN_T… 

---

pom.xml

(cherry picked from commit 9e562f231ff3ad0933481330ef7ea2b3565aa01c)

Bump Tika version to 1.26

---

pom.xml
repository/src/main/java/org/alfresco/repo/content/transform/AbstractLocalTransform.java
repository/src/main/java/org/alfresco/repo/content/transform/DummyTransformServiceRegistry.java
repository/src/main/java/org/alfresco/repo/content/transform/LocalTransform.java
repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
repository/src/main/java/org/alfresco/repo/rendition2/SwitchingTransformServiceRegistry.java
repository/src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
repository/src/test/java/org/alfresco/repo/rendition2/TestTransformServiceRegistry.java

Added isSupported(CoreFunction function, String transformerName) and isSupported(CoreFunction function, LocalTransform transform) ready for work on the ACS-2493 & ACS-2494.

ACS-2498 Add coreVersion to T-Engine config

---

repository/src/main/resources/alfresco/bootstrap/sitesSpace.xml
repository/src/test/java/org/alfresco/repo/importer/ImporterComponentTest.java
repository/src/test/resources/org/alfresco/repo/importer/import_not_indexed_subfolder.xml

Added the required `indexControl` aspect and related properties to make sure that hidden nodes created at bootstrap time won't be indexed in ElasticSearch.

ACS-2276: Add missing indexControl on hidden nodes to avoid ElasticSearch indexing

---

pom.xml
repository/pom.xml

Follow-on to https://github.com/Alfresco/alfresco-community-repo/pull/977 (to update from Gytheio 0.13 to 0.16)
Hence, we will have:
- Gytheio 0.16
- Camel 3.15.0 (including Netty 4.1.73.Final)

ACS-2476: Update to Camel 3.15.0

---

data-model/src/main/java/org/alfresco/repo/content/ContentRestoreParams.java
data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
data-model/src/main/java/org/alfresco/repo/content/ObjectStorageProps.java
data-model/src/main/java/org/alfresco/service/cmr/repository/ArchivedIOException.java
data-model/src/main/java/org/alfresco/service/cmr/repository/RestoreInProgressException.java
remote-api/src/main/java/org/alfresco/rest/api/ContentStorageInformation.java
remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
remote-api/src/main/java/org/alfresco/rest/api/impl/DownloadsImpl.java
remote-api/src/main/java/org/alfresco/rest/api/model/ArchiveContentRequest.java
remote-api/src/main/java/org/alfresco/rest/api/model/RestoreArchivedContentRequest.java
remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeStorageInfoRelation.java
remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsStorageInfoRelation.java
remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/ArchivedContentException.java
remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/RestoreInProgressException.java
repository/src/main/java/org/alfresco/repo/content/AbstractRoutingContentStore.java
repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
repository/src/main/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStore.java
repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java

As agreed, we are ready to remove `@Experimental` annotation from objects and methods related to Storage Object Properties (list properties, archive content, restore content from archive etc.).

ACS-2348: Removing `@Experimental` annotation on Storage Properties

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/RenditionIntegrationTests.java
pom.xml

This change prevents the creation of an existing rendition. There have been cases where a test has tried to re-create an existing rendition, sometimes causing an error in the test.

ACS-2674 - fix/ACS-2674_delete_existing_rendition

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/ActionsTests.java
remote-api/src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
remote-api/src/main/resources/alfresco/public-rest-context.xml

Implemented preventing private action execution from the V1 HTTP API. Added end-to-end test method.

[ACS-2747] Prevent private action execution from the V1 HTTP API

---

repository/src/main/java/org/alfresco/repo/content/transform/LocalPipelineTransform.java
repository/src/main/java/org/alfresco/repo/search/impl/DbCmisQueryLanguage.java
repository/src/main/java/org/alfresco/repo/search/impl/DbOrIndexSwitchingQueryLanguage.java
repository/src/main/java/org/alfresco/repo/search/impl/DisabledFeatureException.java
repository/src/main/java/org/alfresco/repo/search/impl/OpenCMISQueryServiceImpl.java
repository/src/main/resources/alfresco/subsystems/Search/common-opencmis-context.xml
repository/src/main/resources/alfresco/subsystems/Search/common-search-context.xml
repository/src/main/resources/alfresco/subsystems/Search/noindex/common-search.properties
repository/src/main/resources/alfresco/subsystems/Search/noindex/noindex-search-context.xml
repository/src/main/resources/alfresco/subsystems/Search/noindex/opencmis-context.xml
repository/src/main/resources/alfresco/subsystems/Search/solr/common-search.properties
repository/src/main/resources/alfresco/subsystems/Search/solr/opencmis-context.xml
repository/src/main/resources/alfresco/subsystems/Search/solr/solr-search-context.xml
repository/src/main/resources/alfresco/subsystems/Search/solr4/common-search.properties
repository/src/main/resources/alfresco/subsystems/Search/solr4/opencmis-context.xml
repository/src/main/resources/alfresco/subsystems/Search/solr4/solr-search-context.xml
repository/src/main/resources/alfresco/subsystems/Search/solr6/common-search.properties
repository/src/main/resources/alfresco/subsystems/Search/solr6/opencmis-context.xml
repository/src/main/resources/alfresco/subsystems/Search/solr6/solr-search-context.xml
repository/src/test/java/org/alfresco/repo/search/SearchServiceTest.java
repository/src/test/java/org/alfresco/repo/search/impl/solr/DbOrIndexSwitchingQueryLanguageTest.java

- branch was renamed hence new PR ( previously https://github.com/Alfresco/alfresco-community-repo/pull/1085 )
- see also PR for alfresco-enterprise-repo
- new generic query.* props
- query.cmis.queryConsistency
- query.fts.queryConsistency
- query.hybrid.enabled
- deprecate current solr.query.* props (eg. upgrade) - default back if not present
- solr.query.cmis.queryConsistency
- solr.query.fts.queryConsistency
- solr.query.hybrid.enabled

ACS-2925: Elasticsearch - refactor DB switching to not use Solr-specific properties / debug log

---

repository/src/main/resources/alfresco/action-services-context.xml

Not much happens in class, check node, create version.
Added Beans including security interceptors, but VersionService has no restrictions and for node service all there is are a few checks, so it likely never was a security issue to begin with.

ACS-3013: Uppercasing services used to allow security proxy

---

repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java

Fixed Intermittent failure (ConcurrentModificationException) caused by a new call to getData() from configScheduler.

ATS-988 Intermittent test failure: End-to-End Tests - AI-Renditions

---

pom.xml

This reverts commit 6320621f0ddc6297ad22ba3d5f3f5499392895b1.
This is necessary because it causes this kind of failure on master: https://app.travis-ci.com/github/Alfresco/alfresco-community-repo/jobs/573746851
Further `mysql-connector-java` upgrades will require more analysis before being merged.
`Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.`

Downgrade mysql-connector-java from 8.0.29 to 8.0.27

---

.travis.yml

Skip execution of MySQL 5 tests on the master branch since ACS 7.3.X does not list MySQL 5 as a supported platform in https://alfresco.atlassian.net/wiki/spaces/CTO/pages/800587/Supported+Platforms+Roadmap.
This will enable further `mysql-connector-java` upgrades, as explained [here](https://alfresco.atlassian.net/browse/ACS-3181) in detail.

ACS-3181 Skip MySQL 5 tests on master

---

remote-api/src/main/java/org/alfresco/rest/api/Rules.java
remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRulesRelation.java
remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
remote-api/src/test/java/org/alfresco/rest/api/nodes/NodeRulesRelationTest.java
repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java

This PR covers following features: 
- endpoint for DELETE single rule
- DELETE /nodes/{folderNodeId}/rule-sets/{ruleSetId}/rules/{ruleId}
- business logic to remove the rule
- unit tests covering above
Not covered - bulk delete rules under rule set or folder.

ACS-3220 Folder rules delete rule v1 API

---

data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java

* ACS-2064 ContentStore.java to require mimetype
- Updates the ContentStore interface to also require a mimetype, deprecates old method signatures
- Original interface methods maintained so code should be backwards compatible
- Implementing classes updated to reflect changes

ACS-2064 DAU: Fix response content type always PDF (#754)

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java

Adding a test for not enough permissions to create a rule with consumer role.

ACS-3227: REST API TAS test for create rule with consumer role.

---

amps/share-services/src/test/java/org/alfresco/slingshot/web/scripts/SlingshotContentGetTest.java
remote-api/src/main/java/org/alfresco/repo/web/scripts/MimeTypeUtil.java
remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentGet.java
remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentInfo.java
remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
remote-api/src/main/java/org/alfresco/rest/api/impl/CustomModelsImpl.java
remote-api/src/main/resources/alfresco/web-scripts-application-context.xml
remote-api/src/test/java/org/alfresco/repo/web/scripts/content/ContentGetTest.java

* Revert "Revert "ACS-3316 Fix HTML sanitisation bypass (#1266)" (#1294)"
This reverts commit 6c407b1ef5b9002534b2e114e186a0e273495d5a.
* ACS-3316 Set node name for download node
* ACS-3316 Update license
Co-authored-by: Damian.Ujma@hyland.com <Damian.Ujma@hyland.com>
(cherry picked from commit cc3f8aaff4b6c3d16473529f97d229a86d241793)

ACS-3316 Fix custom models downloading and XSS Backport

---

pom.xml

Bumping Alfresco JLAN to 7.2, which includes fixes for FTP+TLS handshake resulting in buffer overflow on Java >= 11.

ACS-3351 Bump Alfresco JLAN to 7.2

---

remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
remote-api/src/test/resources/publicapi/upload/Test Download (1).txt

MNT-23103 Change encoder for content disposition filename to be consistent with RFC5987.
Add test covering filename encoding.

MNT-23103 - Downloading a document replaces filename having space with + character

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
remote-api/src/main/java/org/alfresco/rest/api/impl/rules/ActionParameterConverter.java
remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionParameterConverterTest.java
remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionPermissionValidatorTest.java
remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java

This PR is a second installment for https://github.com/Alfresco/alfresco-community-repo/pull/1305.
This PR roughly consists of:
- initial TAS tests for create rule with multiple actions
- action parameters mappings for rule retrieval + unit tests
- rule/action validations for rule update + unit tests

ACS-3429, ACS-3336: Rule action mappings (create), validations (update) - part 2

---

repository/src/main/java/org/alfresco/repo/security/authentication/ldap/LDAPInitialDirContextFactoryImpl.java
repository/src/main/resources/alfresco/cache-context.xml
repository/src/main/resources/alfresco/caches.properties
repository/src/main/resources/alfresco/subsystems/Authentication/common-ldap-context.xml
repository/src/main/resources/alfresco/subsystems/Authentication/ldap-ad/ldap-ad-authentication.properties
repository/src/main/resources/alfresco/subsystems/Authentication/ldap/ldap-authentication.properties

Added the property below to give the ability to enable/disable LDAP checks (by default is true):
> ldap.initial.checks.enabled
The goal is to allow the checks to run only in one cluster node, disabling them in the other cluster members and preventing the configured principal account from being locked due to invalid attempts.
A cluster aware cache was also added to store the checks that have been executed already, so they won’t be executed again if some configuration is changed in the admin console, however, if, for example, the host or port change, the checks will be performed again.

[MNT-21377] Prevent LDAP checks from running multiple times

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
remote-api/src/main/java/org/alfresco/rest/api/model/rules/Action.java

It will always be set to 'Rule' anyway.

ACS-3536 Omit actionContext for rules.

---

repository/pom.xml

Record of non-transitive netty dependencies to be used in AMPs

ACS-3402: Add actual dependency, not just dependencyManagement

---

amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/alfresco-global.properties
amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/patch/rm-patch-v35-context.xml
amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatch.java
amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatchUnitTest.java

* Added batching capability to process records in hold
* Changed the retrieval of child assocs witout preload to not fill up the caches when we have very big holds
* Added property rm.patch.v35.holdNewChildAssocPatch.batchSize to be able to configure the batchSize

MNT-23174 - RM upgrade from 3.4.1.1 to 11.153 fails

---

repository/src/main/java/org/alfresco/repo/module/DeprecatedModulesValidator.java
repository/src/main/resources/alfresco/messages/module-messages.properties
repository/src/main/resources/alfresco/module-context.xml
repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
repository/src/test/java/org/alfresco/repo/module/DeprecatedModulesValidatorTest.java

Has been tested manually:
- without SAML ✔️
- with SAML (correctly halts the bootstrap while presenting an exception such as `java.lang.IllegalStateException: The following deprecated modules are installed: Alfresco SAML Repository AMP Module 1.2.2. Please remove these AMPs in order to continue.`) ✔️ 
It's supposed to be extensible and will work with future module deprecations as well, featuring composite error messages such as e.g.: `The following deprecated modules are installed: Alfresco SAML Repository AMP Module 1.2.2, Alfresco Office Services Module 1.4.2. Please remove these AMPs in order to continue.`  _(just an example, AOS is not deprecated)_.

ACS-3594 Add mechanism to deprecate modules within the Repo

---

amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeleteRecordTests.java
amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/alfresco-global.properties
amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/patch/rm-patch-v35-context.xml
amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatch.java
amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatchUnitTest.java

* Added batching capability to process records in hold
* Changed the retrieval of child assocs witout preload to not fill up the caches when we have very big holds
* Added property rm.patch.v35.holdNewChildAssocPatch.batchSize to be able to configure the batchSize
* Adapt mocks on unit test to the new calls
(cherry picked from commit a512c3443c63c778f0c5bb5b112dea3c3058a04d)

MNT-23174 - RM upgrade from 3.4.1.1 to 11.153 fails (#1434)

---

remote-api/src/main/java/org/alfresco/repo/webdav/WebDAVServlet.java
remote-api/src/main/resources/alfresco/remote-api-context.xml
remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
remote-api/src/test/java/org/alfresco/repo/webdav/WebDAVInsecurePostMethodTest.java
repository/src/main/resources/alfresco/repository.properties

Adding allowInsecurePOSTMethod flag for webDAV. When the POST method is disable, it returns 405 status code.

ACS-3635 Alfresco WebDAV CSRF - allowInsecurePOSTMethod flag

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java

- adding "alwaysRun = true" to @BeforeMethod due to failing acs-packaging "REST API TAS tests with AIMS"

ACS-3620: E2Es - API for manual triggering rules on a folder

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java

This PR introduces tests for manual triggering of rules on a folder in the case of a broken rule (e.g. deleted destination folder for a copy rule)

ACS-3699: Add test with broken copy action

---

repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java

The problem was that when the response is being built, one of the facet fields filtered by "creator" was returning the expected fields **plus** a null JSONObject. Since the code is expecting a String, an exception was being thrown for this null JSONObject and it would continue the execution without adding any values to the map `fieldFacets` that is then added to the response. This issue is fixed simply by adding a condition that tests if the facet fields are null.

MNT-23276 - Protect from null facet names

---

repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java

This is the same issue of the previous PR https://github.com/Alfresco/alfresco-community-repo/pull/1534. I was disregarding the null value, but it turns out that the null value needs to be considered after all. The facet name should be the string "Null" in case of being null instead of being ignored.

MNT-23276 - The null facet name should be considered

---

repository/src/main/java/org/alfresco/repo/content/transform/RemoteTransformerClient.java

* Public method getRequestEntity that receives the content reader remains the same
* Created private method getRequestEntity that receives an input stream
* request method manages the input stream resource, closing it in the end avoiding hanging connections when AIO is unresponsive or down

MNT-23108 - Manage contentStream resource closure

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetInheritedRulesTests.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
remote-api/src/main/resources/alfresco/public-rest-context.xml
remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java

This PR introduces changes to avoid non-inheritable rules appearing in inherited rule sets. This is the fix to the following JIRA issue [https://alfresco.atlassian.net/browse/ACS-3964](https://alfresco.atlassian.net/browse/ACS-3964)

ACS-3964: fix for non-inheritable rules still appearing in inherited rule sets

---

packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java

This PR introduces changes aiming to fix the bug described in this ticket [https://alfresco.atlassian.net/browse/ACS-4064](https://alfresco.atlassian.net/browse/ACS-4064).

ACS-4064: fix for linking from a folder with inherited rules

---

packaging/war/src/main/webapp/index.jsp
pom.xml

* [MNT-22437] Remove ACS version from landing page
* [MNT-22437] Bump surf-webscripts to 8.33
(cherry picked from commit ace46915409e2c48a0e054337b8bb0882444b8bf)
[MNT-22437]: https://alfresco.atlassian.net/browse/MNT-22437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-22437]: https://alfresco.atlassian.net/browse/MNT-22437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MNT-22437] Remove ACS version from landing page (#1480)

---

pom.xml

We need to replace the `1.5.0-DEV-LOG4J2` version with `1.6.0-A1` version.

ACS-4142 Update AOS version

---

packaging/tests/scripts/output_tests_run.sh
packaging/tests/tas-webdav/src/test/java/org/alfresco/webdav/WebDavTest.java

While working on the Github Actions migration, I discovered a lack of executed tests logs in the `after_success` phase for **WebDAV TAS tests**. We need to implement logger as it is in other classes e.g. [IntegrationTest.java](https://github.com/Alfresco/alfresco-community-repo/blob/master/packaging/tests/tas-integration/src/test/java/org/alfresco/tas/integration/IntegrationTest.java#L97)
Here is an example job without the output for the WebDAV TAS tests: https://app.travis-ci.com/github/Alfresco/alfresco-community-repo/jobs/591283904#L1891
Here is a result after changes: https://app.travis-ci.com/github/Alfresco/alfresco-community-repo/jobs/591292739#L1891

ACS-3841 Add missing logs for WebDAV TAS tests

---

packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryLinkBodyModel.java
packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Node.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/UpdateCategoriesTests.java
remote-api/src/main/java/org/alfresco/rest/api/Categories.java
remote-api/src/main/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelation.java
remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
remote-api/src/main/java/org/alfresco/rest/api/model/Category.java
remote-api/src/main/resources/alfresco/public-rest-context.xml
remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java

POST /nodes/{nodeId}/category-links
https://alfresco.atlassian.net/browse/ACS-4034
- added also one TAS test for update category covering repeated name case
[ACS-4034]: https://alfresco.atlassian.net/browse/ACS-4034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACS-4034: Assign a piece of content to a category

---

repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrCategoryServiceImpl.java
repository/src/test/java/org/alfresco/repo/search/impl/solr/SolrCategoryServiceImplTest.java

This PR (although not directly) is introducing changes for getting top categories in Elasticsearcgh setup. 
- created a common method to create search query parameters for top categories in `AbstractCategoryServiceImpl`
- fixed a (most common) case where `cm:generalclassifiable` aspect is used to get top categories
- added unit tests (E2E aren't yet to be added as this implementation is not used anywhere yet)
This PR makes it possible to query top categories with SOLR search in place which didn't seem to work properly before.
Another PR in ent-repo will be submitted to cover ES part of the search once this one is merged.

ACS-4160: Fixing and making GetTopCategories more re-usable

---

repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
repository/src/main/resources/alfresco/repository.properties

* [MNT-23396] Change call stack depth limit to be only applied to custom scripts (as memory and time limits)
* [MNT-23396] Changed how memory usage is obtained
* [MNT-23391] Only clean scope if script is not considered secure (custom script)
(cherry picked from commit 95ab83d2b1bebf78271395cbadb17f80ba989d4e)
[MNT-23396]: https://alfresco.atlassian.net/browse/MNT-23396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-23396]: https://alfresco.atlassian.net/browse/MNT-23396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-23391]: https://alfresco.atlassian.net/browse/MNT-23391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MNT-23396] [MNT-23391] Change call stack depth limit to be only applied to custom scripts / Clean scope only for custom scripts (#1592)

---

packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Node.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/RenditionIntegrationTests.java

Improve the retry logic of the rendition API tests to reduce the chance of failing tests on https://github.com/Alfresco/terraform-alfresco-pipeline/actions.
This also addresses [ACS-4433](https://alfresco.atlassian.net/browse/ACS-4433).
[ACS-4433]: https://alfresco.atlassian.net/browse/ACS-4433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACS-4177 Improve rendition API tests retry logic

---

packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Node.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
remote-api/src/main/java/org/alfresco/rest/api/Categories.java
remote-api/src/main/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelation.java
remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java

Remove a piece of content from a category - DELETE /nodes/{nodeId}/category-links/{categoryId}
[https://alfresco.atlassian.net/browse/ACS-4035](https://alfresco.atlassian.net/browse/ACS-4035)

ACS-4035: support for removing a piece of content from a category

---

.github/workflows/ci.yml
.github/workflows/master_release.yml

Bumping alfresco-build-tools actions to v1.32.0 and updating the veracode action accordingly.

ACS-3750 Update alfresco-build-tools to v1.32.0

---

pom.xml

This PR is to bump Camel version to `3.20.2` and Gythetio to `0.18`.

ACS-4842 Upgrade Camel and Netty stack

---

pom.xml

Bump json-path and json-smart to the latest available versions.

ACS-4970 Bump json-path to 2.8.0 and json-smart to 2.4.10

---

repository/src/main/resources/alfresco/repository.properties

since the only difference is the number of connections, which doesn't work in community-repo due to how the http clients are created per request of transform

Set property values to the ones being set for sharedFileStoreConnector

---

pom.xml

This reverts commit 06fdc4302e688412e6aa9ff23e862900b0b1858c.
Seems to have broken the CI/CD in acs-packaging, let's try reverting it.

Revert "Bump docker-maven-plugin from 0.42.0 to 0.42.1 (#1866)"

---

pom.xml

Again. It seems the new dmp patch version wasn't causing the issue, that seems related to yum unavailability instead. cc: @mstrankowski 
This reverts commit 2fcf1bd2d59d20727812df03891b3ac7f3a95edd.

Bump docker-maven-plugin from 0.42.0 to 0.42.1

---

remote-api/src/main/java/org/alfresco/rest/api/Categories.java
remote-api/src/main/java/org/alfresco/rest/api/Tags.java
remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
remote-api/src/main/java/org/alfresco/rest/api/tags/TagsEntityResource.java
remote-api/src/test/java/org/alfresco/rest/api/CategoriesUnitTests.java
remote-api/src/test/java/org/alfresco/rest/api/TagsUnitTests.java
repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
repository/src/main/java/org/alfresco/repo/tagging/TaggingServiceImpl.java
repository/src/main/java/org/alfresco/service/cmr/search/CategoryService.java
repository/src/main/java/org/alfresco/service/cmr/tagging/TaggingService.java

Removed only annotations put on Tags & Categories related code.
Folder rules are still `@Experimental` as we haven't made the API for them public.

ACS-5265: Removing @Experimental flag + some import cleanup

---

packaging/tests/tas-cmis/pom.xml

Removing the `resteasy` dependency which seems to be unused by `tas-cmis`.

ACS-4955 Remove unused resteasy dependency

---

packaging/tests/tas-restapi/pom.xml

Causes failures in enterprise-repo AGS tests such as https://github.com/Alfresco/alfresco-enterprise-repo/actions/runs/5045123519/jobs/9050228613#logs and the Elasticsearch equivalent suite.
There are some breaking changes between 4.5.6 and 4.5.14 related to empty paths behavior in REST APIs, it might be related to that. We should rollback until we can dedicate some time for further analysis/troubleshooting.

ACS-4955 Restore httpclient-osgi 4.5.6

---

pom.xml

This reverts commit e00959a089ffbca04a7e5a7a5836c09e29281329.
Causes issues in All AMPs tests, most likely related to an incompatibility within this specific set of Azure/Camel/Netty libraries.
acs-packaging master is currently hanging while trying to start the All AMPs docker compose, with no meaningful errors. Reverting the Camel bump makes it pass: https://github.com/Alfresco/acs-packaging/actions/runs/5046989115/jobs/9053235298?pr=2479.

Revert "Bump dependency.camel.version from 3.20.2 to 3.20.4 (#1905)"

---

repository/src/main/java/org/alfresco/repo/security/sync/ldap/LDAPUserRegistry.java

Removing the limit allows to keep the synchronization getting pages of `ldap.synchronization.queryBatchSize` entries until it's finished, otherwise, the synchronization only gets the max of users as defined in `ldap.synchronization.queryBatchSize`.
I have worked on an unit test implementation, however, I've realized it wouldn't be possible to maintain it as it was always succeeding (regardless the fix being in place or not). The reason is because the real time synchronization uses the [PersonCollection](https://github.com/Alfresco/alfresco-community-repo/blob/90e9764d63946d35ed5f1e32c294b9413cabef5b/repository/src/main/java/org/alfresco/repo/security/sync/ldap/LDAPUserRegistry.java#L1472) but the test synchronization doesn't. 
- [LDAPUserRegistry#getPersons(Date)](https://github.com/Alfres …

[MNT-23665] Removed search controls count limit

---

remote-api/src/main/java/org/alfresco/rest/api/search/model/FacetField.java

After MNT-23276, a "Null" value was introduced but the facetQuery does not reflect how to query nodes with that facet

MNT-23451 filterQuery for facet "Null"

---

remote-api/src/main/java/org/alfresco/rest/api/search/model/FacetField.java

After MNT-23276, a "Null" value was introduced but the facetQuery does not reflect how to query nodes with that facet
(cherry picked from commit d46ae1634f0ffc4ac5e5082d9036b09d2452b285)

MNT-23451 filterQuery for facet Null (#1764)

---

data-model/src/main/java/org/alfresco/service/cmr/search/SearchParameters.java
packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/search/RestRequestLimitsModel.java
packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/search/SearchRequest.java
remote-api/src/main/java/org/alfresco/rest/api/search/impl/SearchMapper.java
remote-api/src/main/java/org/alfresco/rest/api/search/model/Limits.java
remote-api/src/test/java/org/alfresco/rest/api/search/SearchMapperTests.java

- SearchParameters - added trackTotalHits (int) attribute
- SearchRequest - Added trackTotalHitsLimit (int) to the Limits attribute and mapped it to the SearchParameters
- Changed the SearchRequest model in TAS to include a new RestRequestLimitsModel that has the new trackTotalHitsLimit attribute
- SearchMapperTests to test the changes in the SearchParameters

ACS-5487 - Track Total Hits on ES

---

data-model/src/main/java/org/alfresco/service/cmr/search/SearchParameters.java
packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/search/RestRequestLimitsModel.java
packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/search/SearchRequest.java
remote-api/src/main/java/org/alfresco/rest/api/search/impl/SearchMapper.java
remote-api/src/test/java/org/alfresco/rest/api/search/SearchMapperTests.java

SearchParameters - added trackTotalHits (int) attribute SearchRequest - Added trackTotalHitsLimit (int) to the Limits attribute and mapped it to the SearchParameters Changed the SearchRequest model in TAS to include a new RestRequestLimitsModel that has the new trackTotalHitsLimit attribute SearchMapperTests to test the changes in the SearchParameters
(cherry picked from commit a1faf97fc517f85774e6dc35ac63ebe0882f4ca9)

ACS-5487 - Track Total Hits on ES (#2041)

---

amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/collaboration/tagQuery.get.js
amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/categorynode.get.js
amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/images.get.js

This also fixes the query logic in two other webscripts. The default boolean operator is OR but these webscripts require AND.

MNT-23763 Fix image preview webscript for use with ES.

---

.github/workflows/ci.yml

GitHub Actions does not provide a regex version of contains and so during the migration from Travis we lost the ability to search for tokens like `[force 7.4.1-A1]`. By loosening the match to just `[force` then we can match both types of token.

ACS-5698 Allow specifying version when performing force release.

---

repository/src/test/java/org/alfresco/repo/lock/LockServiceImplTest.java
repository/src/test/java/org/alfresco/repo/rule/RuleServiceImplUnitTest.java

This update is just improving code quality of 2 test classes, I managed to get rid of more than 260 PMD issues.
Bigger changes:
Before there were only 3 tests annotated `@Test` and only these were run. Now all tests run.
There were some empty tests annotated as `TODO` from 2005 so I decided to delete these as for more than 18 years no one has wrote them.

ACS-5449 Code quality improvements to LockServiceImplTest & RuleServiceImplUnitTest

---

.github/workflows/ci.yml

This also updates the default ruleset location from AlfrescoLabs/pmd-ruleset to Alfresco/pmd-ruleset.

PRODENG-222 Update to PMD 7.

---

data-model/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/lucene/LuceneConjunction.java
data-model/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/lucene/LuceneQuery.java

Remove unused list of constraints.
Only add match all clause once if necessary.

ACS-2699 Update logic around + and - for lucene queries.

---

repository/src/main/java/org/alfresco/repo/action/executer/ImporterActionExecuter.java

Replaced the illegal characters from the filename while extracting File from zip in ImporterActionExecuter

MNT-23476 Unable to unzip files in Share if it contains a document with a filename containing an accent

---

repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java

Added the Null check for the ParameterDefinition in the method isValidScriptRef

[MNT-23107] The scriptLocation property is not picked up when set in a bean definition

---

.github/workflows/ci.yml

Nb. The UnnecessaryImport rule has been disabled since we're not currently including the full classpath - see https://github.com/Alfresco/pmd-ruleset/pull/3

PRODENG-222 Fail builds based on PMD scan.

---

amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java

- disabling failing tests
https://alfresco.atlassian.net/browse/ACS-6073

ACS-6073: DispositionScheduleLinkedRecordsTest - tests fail over and over again

---

.github/workflows/ci.yml
.github/workflows/master_release.yml

This should help making the build faster and more stable in cases where we're close to saturating the disk space of the runner.

ACS-6122 Free up GHA runner disk space

---

repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java

* [MNT-23478] AsynchronousExtractor - Fix rendition obtaining
* [MNT-23478] Only use default options if no rendition is found. PMD scan change.
(cherry picked from commit 3bd3689d809dfe253908e1e65c3c044acf948d3f)
[MNT-23478]: https://alfresco.atlassian.net/browse/MNT-23478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-23478]: https://alfresco.atlassian.net/browse/MNT-23478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MNT-23478] AsynchronousExtractor - Fix rendition obtaining (#2288)

---

remote-api/src/main/java/org/alfresco/rest/framework/jacksonextensions/JacksonHelper.java
remote-api/src/test/java/org/alfresco/rest/framework/tests/core/ExecutionTests.java
repository/src/main/java/org/alfresco/repo/domain/propval/AbstractPropertyValueDAOImpl.java

- Handle JsonMappingException and JsonGenerationException by throwing an IOException so we do not risk sending a partial JSON response
- Added logging to alert when a null key is found

MNT-23927 Handle JsonMappingException and JsonGenerationException

---

.gitignore
repository/scripts/hazelcast-init/alfresco-hazelcast-template.xml
repository/scripts/hazelcast-init/ci-caches.properties
repository/scripts/hazelcast-init/generate-hazelcast-config.py
repository/src/main/resources/alfresco/caches.properties

This should make sure that all customers have access to this script. This is really only useful for enterprise customers which are willing to run their own external Hazelcast cluster, but it won't be accessible to them if it's in the enterprise-repo instead.

ACS-6329 Move generate-hazelcast-config.py to community-repo

---

.github/workflows/ci.yml
scripts/ci/docker-compose/docker-compose.yaml

Switching from IDS 2.0.0 to Keycloak 21.1.2 as a test component due to IDS reaching End of Life status.

 ACS-5925 Switch from IDS 2.0.0 to Keycloak 21.1.2 

---

core/src/test/java/org/alfresco/util/VersionNumberTest.java

As per [this comment](https://alfresco.atlassian.net/browse/ACS-6402?focusedCommentId=1223553) in ACS-6402 - I am adding tests which explicitly cover cases we may experience after applying new versioning schema in ACS on module compatibility checks.

ACS-6402: Add tests covering module compatibility check for new ACS versioning schema

---

repository/src/main/resources/alfresco/repository.properties

When this PR is merged, propagated downstream and ACS docker image is built then a [PR](https://github.com/Alfresco/terraform-alfresco-pipeline/pull/1350) in `terraform-alfresco-pipeline` project needs to be merged as well.

ACS-6406: Bumping down version.schema to 19100 for ACS 23.2

---

remote-api/src/main/java/org/alfresco/rest/api/NetworkWebScriptGet.java
remote-api/src/main/java/org/alfresco/rest/api/NetworksWebScriptGet.java
remote-api/src/main/java/org/alfresco/rest/api/PublicApiTenantWebScriptServletRuntime.java
remote-api/src/main/java/org/alfresco/rest/api/search/SearchApiWebscript.java
remote-api/src/main/java/org/alfresco/rest/api/search/SearchSQLApiWebscript.java
remote-api/src/main/java/org/alfresco/rest/framework/tools/ResponseWriter.java
remote-api/src/main/java/org/alfresco/rest/framework/webscripts/AbstractResourceWebScript.java

* Add WebScriptRequest to the methods that call the render exception so we can log more info on the request when an error occurs.
* Add request uri, user and status code to the logging
* Always log on exception but only show stack trace on debug or on internal server exception

MNT-24094 - improve remote-api logging on error

---

amps/ags/rm-automation/rm-automation-community-rest-api/pom.xml
data-model/pom.xml
mmt/pom.xml
pom.xml
repository/pom.xml

Bumping a bunch of intertwined/related dependencies together to make sure everything works as intended.
---
**Propagation tests**:
- [ent-repo](https://github.com/Alfresco/alfresco-enterprise-repo/pull/1812)
- [acs-packaging](https://github.com/Alfresco/acs-packaging/pull/2677)
- [acs-comm-packaging](https://github.com/Alfresco/acs-community-packaging/pull/1546)
---
**Related PRs**:
- [ent-share](https://github.com/Alfresco/alfresco-enterprise-share/pull/579) (to satisfy the new `maven-enforcer-plugin` requirements)

ACS-6653 Bump Tika, POI, bouncycastle, commons-compress, xmlbeans

---

remote-api/src/main/java/org/alfresco/rest/api/impl/GroupsImpl.java
repository/src/main/java/org/alfresco/repo/security/permissions/impl/acegi/ACLEntryAfterInvocationProvider.java

Added a fix for `String` to `NodeRef` cast exception when `returnedObject` contains pair of strings.

[ACS-5506] Fix string to node ref cast exception

---

remote-api/src/main/java/org/alfresco/repo/web/scripts/solr/NodesMetaDataGet.java

This PR provides a very minor/trivial change that will have ACS actually use the parameter `includeChildAssociations` as provided by Search Services since at least version 1.4.2 (https://github.com/Alfresco/SearchServices/commit/943fafcca383a995db221805fed2cd9036ec66e2). This will significantly reduce the overhead when indexing metadata changes on any node that contains large amount of child nodes as combined with the `includeChildIds` flag which is already handled and provided as `false` as well, this change results in the elimination of the extremely expensive `getChildAssocs` call in the `SOLRTrackingComponentImpl` `getNodesMetadata` method.

Map includeChildAssociations request parameter

---

pom.xml

Bumps org.apache.commons:commons-compress from 1.25.0 to 1.26.0.

Bump org.apache.commons:commons-compress from 1.25.0 to 1.26.0 (#2454)

---

repository/src/main/java/org/alfresco/repo/security/sync/ChainingUserRegistrySynchronizer.java

* [MNT-24072] Retain existent users and groups so parent associations can be created
* [MNT-24072] Using person/authority 'exists' methods instead
* [MNT-24072] Added code to rezone users/groups (who already exist and are part of AUTH.ALF zone) that have parent associations to create
* [MNT-24072] PMD scan changes
* [MNT-24072] Added a validation to prevent an authority from being added to zones where already is
(cherry picked from commit 71b69529c660ccc9eeecd22791999ba0b02b00f7)
[MNT-24072]: https://alfresco.atlassian.net/browse/MNT-24072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-24072]: https://alfresco.atlassian.net/browse/MNT-24072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[MNT-24072] Retain users/groups (who are already exist and are part of AUTH.ALF zone) so parent associations can be created (#2414)

---

.github/workflows/ci.yml

The Veracode Pipeline SAST Scan started timing out after an hour and no solution was found on our side. This is meant to be temporary and to be restored once we resolve this issue with the help of Veracode Support.
https://alfresco.atlassian.net/browse/ACS-6931

ACS-6931 Temporarily turn off SAST Scan

---

pom.xml

Bumping tika version to 2.9.2.
Dependency Tree: 
+- org.apache.tika:tika-parser-mail-module:jar:2.9.2:compile
[INFO] |  |  +- org.apache.tika:tika-parser-mail-commons:jar:2.9.2:compile
[INFO] |  |  |  +- org.apache.james:apache-mime4j-core:jar:0.8.11:compile
[INFO] |  |  |  |  \- (commons-io:commons-io:jar:2.14.0:compile - version managed from 2.11.0; omitted for duplicate)
[INFO] |  |  |  \- org.apache.james:apache-mime4j-dom:jar:0.8.11:compile
[INFO] |  |  |     +- (org.apache.james:apache-mime4j-core:jar:0.8.11:compile - omitted for duplicate)
Full dependency tree: [tree.log](https://github.com/Alfresco/alfresco-community-repo/files/14929671/tree.log)

[ACS-6935] Update tika version to 2.9.2

---

pom.xml

Adding an explanation of why we need the json-path dependency in ACS.

[ACS-6776] Add comment to json-path dependency

---

repository/src/main/resources/alfresco/repository.properties

the version.schema in 7.3.N was the same as in 7.3.1, bumping it in preparation of the 7.3.2 release

ACS-7683 Bump version.schema to 17200 for 7.3.2

---

pom.xml
repository/pom.xml

Bumping:
- guava version to **33.1.0-jre**
- webscripts version to **8.50**
Full dependency tree: [dependency_tree.log](https://github.com/Alfresco/alfresco-community-repo/files/15130363/dependency_tree.log)

[ACS-7646] Bump guava version to 33.1.0-jre

---

repository/src/main/java/org/alfresco/repo/transfer/HttpClientTransmitterImpl.java
repository/src/main/java/org/alfresco/util/json/ExceptionJsonSerializer.java

* Mark method deserialize in ExceptionJsonSerializer as deprecated
* Remove usage of jsonErrorSerializer
(cherry picked from commit c31158a11303a0da88e3ba22be387f6ef21493ae)

MNT-24321 Transfer Service Exception Handling (#2573)

---

amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/hold/AddToHoldsBulkV1Tests.java

Fix for the following failure: https://github.com/Alfresco/alfresco-enterprise-repo/actions/runs/9270020015/job/25540583835#step:9:3592
Instead of removing permissions for particular user we should set only read permission (SiteConsumer) for one file to cause one error in the bulk operation. The test failed because removing read permission was respected by the search service before the bulk operation execution.

ACS7587 Fix intermittent failure

---

.github/workflows/ci.yml

Since the last Veracode engine update fixed the issue with scanning community-repo, we can reenable the SAST Scan here

ACS-6931 Re-enable Veracode SAST Scan

---

pom.xml
repository/pom.xml

The outdated version of `jakarta.transaction-api` brought in by `commons-dbcp2` causes 3rd party repositories that import `alfresco-repository` to potentially use this outdated version instead of the expected `2.0.1`.
This could be fixed at the Share level and it would avoid more libraries potentially bringing in discording versions of `jakarta.transaction-api`, however fixing it there would also mean that anyone else importing `alfresco-repository` would have to make the same change. So it is safer to do it here.
Tested by building Share with the latest local SNAPSHOT of community-repo with the changes presented in this PR:
**NOTE: all tests in this PR passed, we can safely ignore ReportPortal-specific failures. The build will be soon improved to disregard ReportPortal reachability …

Exclude jakarta.transaction-api from commons-dbcp2

---

pom.xml

The Jackson upgrade would break compatibility with Azure Connector vs older ACS versions, see https://github.com/Alfresco/alfresco-azure-connector/actions/runs/9898746940/job/27346225378?pr=991 and https://hyland.atlassian.net/issues/ACS-8397

Rollback Jackson from 2.17.2 to 2.15.2

---

repository/src/main/java/org/alfresco/ibatis/IdsEntity.java
repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
repository/src/main/resources/alfresco/public-services-security-context.xml
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java

- Limit the job execution to a configurable amount of nodes (system.fixedACLsUpdater.maxItems)
- Add query template select_NodesWithAspectIds_Limited that does a left join with alf_store and limits the results
- Query executions by the job are now limited to maxItemBatchSize
- Imposing the order by in the query is now configurable (system.fixedACLsUpdater.orderNodes)

MNT-24503 - Improve FixedAclUpdater

---

amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/patch/v33/RMv33HoldAuditEntryValuesPatchUnitTest.java
remote-api/src/main/java/org/alfresco/rest/api/impl/AuditImpl.java
repository/src/main/java/org/alfresco/repo/audit/AuditComponent.java
repository/src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java
repository/src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java
repository/src/main/java/org/alfresco/repo/domain/CrcHelper.java
repository/src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java
repository/src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/propval/PropertyStringValueEntity.java
repository/src/main/java/org/alfresco/service/cmr/audit/AuditService.java

https://hyland.atlassian.net/browse/MNT-24137

[MNT-24137] Audit Issue Internal Server Error fix

---

packaging/docker-alfresco/Dockerfile
repository/src/main/java/org/alfresco/ibatis/IdsEntity.java
repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
repository/src/main/resources/alfresco/public-services-security-context.xml
repository/src/main/resources/alfresco/repository.properties
repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java

* Limit the job execution to a configurable amount of nodes (system.fixedACLsUpdater.maxItems)
* Add query template select_NodesWithAspectIds_Limited that does a left join with alf_store and limits the results
* Query executions by the job are now limited to maxItemBatchSize
* Imposing the order by in the query is now configurable (system.fixedACLsUpdater.orderNodes)
(cherry picked from commit 9ed29967b77e51ec5e2b69e51bd2b72da73523bb)

MNT-24503 - Limits on FixedAclUpdater (#2788)

---

remote-api/src/main/java/org/alfresco/rest/api/impl/PeopleImpl.java
remote-api/src/main/resources/alfresco/public-rest-context.xml
repository/src/main/java/org/alfresco/repo/security/authentication/AuthenticationContextImpl.java
repository/src/main/resources/alfresco/authentication-services-context.xml
repository/src/main/resources/alfresco/repository.properties

* [MNT-24513] Immutable user: allow enabled status change
* [MNT-24513] Created 'allow.immutable.user.enabled.status.update' to control whether an immutable user enabled status can be changed or not
* [MNT-24513] Regardless user details enabled status, the person nodeRef enabled status is also checked
* [MNT-24513] Prevent LDAP users from being disabled. Changed variable name.
(cherry picked from commit 8a61badabc1f3f7e36af345e70906ea4d8394cef)
[MNT-24513]: https://hyland.atlassian.net/browse/MNT-24513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-24513]: https://hyland.atlassian.net/browse/MNT-24513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNT-24513]: …

[MNT-24513] Immutable user (IDS): allow to change enabled status (#2789)

---

repository/src/main/resources/alfresco/core-services-context.xml

We faced an exception due to the absence of a bean named 'search.suggesterService'. After adding the 'search.suggesterService' bean, the issue has been resolved, and everything is working as expected.

Suggester feature in Share

---

.github/workflows/ci.yml
.github/workflows/master_release.yml

- Migrate from **Node16** to **Node20**.
- Bump `actions/upload-artifact` and `actions/download-artifact` from v3 to v4.
- Additionally: upgrading the version to the latest for other actions from the **alfresco-build-tools**.

ACS-8670 Deal with upcoming GitHub Actions deprecations

---

.github/workflows/ci.yml
.github/workflows/master_release.yml

- Migrate from **Node16** to **Node20**.
- Bump `actions/upload-artifact` and `actions/download-artifact` from v3 to v4.
- Additionally: upgrading the version to the latest for other actions from the **alfresco-build-tools**.

ACS-8670 Deal with upcoming GitHub Actions deprecations 

---

remote-api/src/main/java/org/alfresco/rest/framework/webscripts/AbstractResourceWebScript.java

* Upon execution error, since there is another retry in transaction inside it can be retried without throwing an error and entering the catch
* Reset the buffered request at the beginning of the transaction so in case of a retry in can be read.

MNT-24441 Transaction Retries From A Behavior Can Fail During REST API Calls

---

remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java

- Obtain site manager authority as system user
- Set site manager permissions as the authenticated user
- Prevent site manager permissions from being removed if inheritance flag is disabled (as it happens in Share)

[MNT-24282] Obtain site manager authority as system and keep site manager permissions when inheritance flag is disabled

---

pom.xml

* [MNT-24590] Bump spring-webscripts to 9.3
(cherry picked from commit d17c11b8ad7150e7008dba5cf4e4df6ec6836752)
[MNT-24590]: https://hyland.atlassian.net/browse/MNT-24590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MNT-24590] Bump surf webscripts to 9.3

---

.github/workflows/ci.yml
.pre-commit-config.yaml
.secrets.baseline
CONTRIBUTING.md
alfresco-formatter.xml
pom.xml
scripts/hooks/check-format-and-headers.sh

* Add precommit for secret scanning, formatting and license header checking.
* Turn off bash debug logging.
* Skip precommit checks that apply to all files.
There are too many violations to run against all files.
(cherry picked from commit b00e11cb6fe312558439cfc8565cf4b8d1e7dca6)

Add precommit for secret scanning, formatting and license header checking.

---

repository/src/main/java/org/alfresco/repo/cache/lookup/EntityLookupCache.java
repository/src/main/java/org/alfresco/repo/domain/contentdata/AbstractContentDataDAOImpl.java
repository/src/test/java/org/alfresco/repo/cache/lookup/EntityLookupCacheTest.java

* On createOrGetByValue in EntityLookupCache, also cache by value
* Created getCachedEntityByValue that attempt to retrieve the value only from cache
* On attempt to create content URL, first check cache before attempting to create in the database avoiding a duplicate key error

MNT-24641 Avoid duplicate key error on content upload

---

repository/src/main/java/org/alfresco/repo/cache/lookup/EntityLookupCache.java
repository/src/main/java/org/alfresco/repo/domain/contentdata/AbstractContentDataDAOImpl.java
repository/src/test/java/org/alfresco/repo/cache/lookup/EntityLookupCacheTest.java

MNT-24641
* On createOrGetByValue in EntityLookupCache, also cache by value
* Created getCachedEntityByValue that attempt to retrieve the value only from cache
* On attempt to create content URL, first check cache before attempting to create in the database avoiding a duplicate key
(cherry picked from commit f4103c242fe71d71957eb378b251e3a0bb812b76)

MNT-24641 Avoid duplicate key error on content upload (#2984)

---

repository/src/main/java/org/alfresco/repo/site/SiteMembership.java

The Site Membership API fails when the last name is null. This fix addresses the issue to ensure that the API can handle cases where the last name field is missing or null without throwing an error.

Fix/MNT-24571-Site Membership API

---

repository/src/main/java/org/alfresco/repo/content/AbstractRoutingContentStore.java

Method requestRestoreContentFromArchive needs to use injected ContentStore

MNT-24753 Restore from Archive when we have multiple content stores

---

pom.xml

It makes enterprise-repository tests fail. See more https://hyland.atlassian.net/browse/ACS-9074

Revert "Bump dependency.log4j.version from 2.23.1 to 2.24.2"

---

pom.xml
repository/src/main/java/org/alfresco/repo/admin/Log4JHierarchyInit.java

JMX support has been disabled by default in `Log4j 24.0.0` version (See: [Release notes](https://logging.apache.org/log4j/2.x/release-notes.html#_jmx_changes))
Added `log4j2.disableJmx=false` system property in `Log4JHierarchyInit` to enable JMX support.
alfresco-enterprise-repo PR: https://github.com/Alfresco/alfresco-enterprise-repo/pull/2282

ACS-9074 Bump log4j to 2.24.2

---

remote-api/src/main/java/org/alfresco/rest/api/impl/AuditImpl.java

https://hyland.atlassian.net/browse/APPS-3129
This issue is happening when appNamePair shortvalue is generated with stringlowercase irrespective of caseSensitive flag, but as per the scenario the appName in audit application is differed by case (Upper vs Lower). 
When its try to get appNamePair for appName its not matching value and its returning null from convertFromRestAuditQueryParameters(parameters) in getAuditEntriesCountByAppAndProperties method in AuditDAOImpl class.
So instead of getting auditEntries by the appKey we are now getting auditEntries by appName it will resolve the issue. Same approch already was there in getAuditEntry method in AuditImpl class.
Tested Scenarios:
1. name="TESTPermissionAudit" key="testpermissionaudit"
2. name="testpermissionaudit" …

[APPS-3152] fix for mnt-24137

---

repository/src/main/java/org/alfresco/repo/node/sizedetails/NodeSizeDetailsServiceImpl.java

https://hyland.atlassian.net/browse/APPS-3154
Here in this ticket, The "numberOfFiles" field in the GET/size-details response does not return accurate data for values exceeding 500.
The root cause appears to be the default limit of 500 in the search parameter when executing size-details for more than 500 files.
To address this issue, I made some changes by taking the value from the "NumberFound" field in the result entity, and it is now working correctly.

[APPS-3154] fix for number of file field in response

---

packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestAuthCodeModel.java
packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestAuthKeyModel.java
packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/People.java
packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/people/deauthorization/community/ReauthorizeSanityTests.java
remote-api/src/main/java/org/alfresco/rest/api/model/AuthCode.java
remote-api/src/main/java/org/alfresco/rest/api/model/AuthKey.java
remote-api/src/main/java/org/alfresco/rest/api/people/PeopleEntityResource.java

Implementation according to https://github.com/Alfresco/rest-api-explorer/pull/222
In community edition endpoins return `HTTP 501 Not implemented`

ACS 9185 implement rest api for reauthorizing a single user

---

.secrets.baseline
amps/ags/rm-community/rm-community-repo/pom.xml
packaging/distribution/src/main/resources/licenses/notice.txt
packaging/tests/tas-integration/pom.xml
pom.xml
repository/pom.xml
repository/src/test/java/org/alfresco/email/server/EmailServiceImplTest.java
repository/src/test/java/org/alfresco/repo/imap/ImapMessageTest.java

Since `subethasmtp` [switched to Jakarta Mail 2.1](https://github.com/davidmoten/subethasmtp/pull/124/files), some tests failed due to the incompatible `com.sun.mail:jakarta.mail` implementation (See: https://github.com/Alfresco/alfresco-community-repo/actions/runs/12918991059/job/36029451587#step:13:603)
This PR is to bump `subethasmtp` version to `7.1.3` and use `org.eclipse.angus:angus-mail:2.0.3` which is a compatible implementation of the [Jakarta Mail Specification 2.1+](https://jakarta.ee/specifications/mail/).
Ref. https://eclipse-ee4j.github.io/angus-mail/

ACS-9199 Bump subethasmtp version to 7.1.3

---

pom.xml

https://hyland.atlassian.net/browse/PRODSEC-9888
https://hyland.atlassian.net/browse/PRODSEC-9867
Issue - The dependency of apache cxf-core 4.0.5 and netty-common 4.1.113.Final contains security vulnerabilities.
we have upgrade the dependency in alfresco-commmunity-repo for cxf- core to 4.1.0 and netty-common to 4.1.117.Final.

[PRODSEC-9888] fix for cxf-core and netty-common

---

amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/action/unlock-document.post.json.js

This PR includes the the changes to revert the commit done as a part of task https://hyland.atlassian.net/browse/AFI-203.
The MNT says that the code should be reverted and the code which was  added earlier must be moved to Google Docs code and leave this resource in Share Services as it was before the commit. So we have reverted the commit.
Created a new task https://hyland.atlassian.net/browse/APPS-3230 to move this code to GoogleDocs. As there is no GoogleDocs Release planned so will take this up in upcoming release.

Revert Unlock Document Changes

---

repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
repository/src/main/java/org/alfresco/repo/event2/EventSender.java
repository/src/main/java/org/alfresco/repo/event2/EventSenderFactoryBean.java

Explanation:
https://hyland.atlassian.net/browse/MNT-24937
community config:
`<bean id="eventSender" class="org.alfresco.repo.event2.EventSenderFactoryBean" autowire="constructor" parent="baseEventSender" />`
enterprise config:
`<bean id="eventSender" class="org.alfresco.enterprise.repo.event2.EnterpriseEventSenderFactoryBean" autowire="constructor" parent="baseEventSender">
<property name="outboxEventSenderFactory" ref="outboxEventSenderFactory" />
</bean>`
[logAfterFixVersion2.txt](https://github.com/user-attachments/files/19486463/logAfterFixVersion2.txt)
[gracefulExitAfterFixVersion2.txt](https://github.com/user-attachments/files/19486462/gracefulExitAfterFixVersion2.txt)
Initial solution:
https://github.com/Alfresco/alfresco-enterprise-repo/pull/2396

[MNT-24937] Fix EventTableOutbox messages flooding the logs on bootstrap failure

---

remote-api/src/main/java/org/alfresco/rest/api/impl/PeopleImpl.java
remote-api/src/main/java/org/alfresco/rest/api/model/Person.java

Allowing admin user to update password when user is already enabled or trying to enable. If admin user tries to update the password by unchecking the enabled checkbox or send enabled flag as false through payload will throw error like "Admin authority cannot be disabled"

[MNT-24146] - Unable to update password for 'admin' user

---

pom.xml

[PRODSEC-10096]-Bump-poi-version to 5.4.1
[PRODSEC-10096]: https://hyland.atlassian.net/browse/PRODSEC-10096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PRODSEC-10096]-Bump-poi-version

---

pom.xml

[PRODSEC-10096]-Bump-poi-version to 5.4.1
[PRODSEC-10096]: https://hyland.atlassian.net/browse/PRODSEC-10096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PRODSEC-10096]-Bump-poi-version-backport

---

amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/action/unzip-to.post.json.js
repository/src/main/java/org/alfresco/repo/action/executer/ImporterActionExecuter.java
repository/src/main/java/org/alfresco/repo/model/filefolder/FileFolderServiceImpl.java
repository/src/main/java/org/alfresco/service/cmr/model/FileExistsException.java
repository/src/main/java/org/alfresco/service/cmr/model/FolderExistsException.java
repository/src/test/java/org/alfresco/repo/action/executer/ImporterActionExecuterTest.java

[ACS-9572] When unzipping, if a file/folder is already there with same name, then throw proper exception and show valid message to user.
[ACS-9572]: https://hyland.atlassian.net/browse/ACS-9572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ACS-9572] show proper message for duplicate unzipping

---

repository/src/main/java/org/alfresco/repo/rendition/executer/AbstractRenderingEngine.java
repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java

https://hyland.atlassian.net/browse/MNT-24172
Based on the implemented code, below are the observations encountered during the execution of the RenditionService2 implementation via the POST- nodes/{nodeId}/renditions and DELETE- nodes/{nodeId}/renditions/{renditionId} endpoints:
The POST endpoint assigns the rn:rendition2 aspect to the respective rendition nodes (e.g., cm:pdf).
After executing the DELETE endpoint, the CONTENT_PROPERTY is removed from the rendition nodes.
When attempting to open the document from Share, a condition for Qname-cm:pdf checks for ASPECT_RENDITION2, during which the CONTENT_PROPERTY is retrieved. However, it returns null, causing the document not to open and resulting in a NullPointerException. Since the CONTENT_PROPERTY is removed during the DELETE operation, …

[fix/MNT-24172-fixRecreationOfRendition2] Backport Fix of recreation of rendition2

---

amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/rm-public-rest-context.xml
amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/rm/rest/api/fileplans/FilePlanRolesRelation.java

This PR is to fix roles access for non-rm users when the file plan ID is used instead of a file plan alias.

ACS-9429 Fix AGS Roles API

---

remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/forms/pickerresults.lib.ftl

This PR resolves an issue where users without access to certain categories could not see any categories in the category picker. Instead of displaying only the categories the user has permission to access, the picker failed completely, resulting in an empty list and log errors.

Backported the MNT-24776

---

remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/forms/pickerresults.lib.ftl

This PR resolves an issue where users without access to certain categories could not see any categories in the category picker. Instead of displaying only the categories the user has permission to access, the picker failed completely, resulting in an empty list and log errors.

Fix category picker visibility to show only permitted categories based on local permissions

---

repository/src/main/java/org/alfresco/repo/site/SiteServiceImpl.java
repository/src/test/java/org/alfresco/repo/site/SiteServiceImplTest.java

This change fixes a broken behavior of `live-search-sites` web script when input contains elastic search reserved character.
The web script calls `org.alfresco.repo.site.SiteServiceImpl#findSites(java.lang.String, int)` to do a query, which eventually looks like:
```{"from":0,"query":{"bool":{"filter":[{"bool":{}}],"must":[{"bool":{"boost":1.0,"must":[{"bool":{"boost":1.0,"should":[{"query_string":{"query":"TYPE:st\\:site"}}]}},{"bool":{"boost":1.0,"should":[{"query_string":{"boost":1.0,"query":"cm%3Aname:-chu*"}},{"query_string":{"boost":1.0,"query":"cm%3Atitle:\\-chu*"}},{"query_string":{"boost":1.0,"query":"cm%3Adescription:\\-chu"}}]}}]}}]}},"size":5,"track_scores":true,"track_total_hits":10000}```
Notice the `-chu` is present 3 times, but the first occurrence is not escaped properly …

ACS-9646 removed extra space that broke the escaping logic

---

pom.xml
repository/pom.xml

Update 1:
We should be using servlet 6 API.
----
`org.apache.commons:commons-fileupload2-jakarta:2.0.0-M1` has a CVE in `commons-fileupload2-core-2.0.0-M1.jar`. Instead of adding explicit updated dependency for core I've updated the dependency it comes with. There is a tiny problem though, because `commons-fileupload2-jakarta` is no longer maintained and instead there are 2 other versions depending on servlet API we're using. Here I have used the servlet5 one, with `commons-fileupload2-jakarta-servlet5`.

PRODSEC-10332 updated commons-fileupload2-jakarta to address cve

---

repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessor.java

`NodePermissionAssessor.getOwner` will be prioritizing owner aspect first and then audit creator as fallback . Similar to `OwnableServiceImpl.getOwner`.

MNT-25150 NodePermissionAssessor.getOwner checks for owner aspect first

---

repository/src/main/java/org/alfresco/repo/node/db/DbNodeServiceImpl.java
repository/src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java

Removing an aspect also removes the properties from that aspect from the node however the onUpdateProperties policies were not being triggered - particularly the event did not contain the information that properties were removed.

ACS-9923 Removing an aspect needs to invoke onUpdateProperties

---

remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/Parameters.java
remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/Params.java

This PR removed invalid T function wrapper import in Parameters interface (and usages of it). The method was supposed to be parametrized and return generic type instead, by coincidence also named T.

ACS-9981 removed invalid T function import in Parameters

---

repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java

Whenever thumbnails were disabled, content indexing and metadata extract/embed was skipped (exception being thrown). Added logic to check if the given transform callback is a text extract transform for content indexing or metadata extract/embed and allow it. Remaining callbacks will result in exception being throw, if thumbnails are disabled.

[ACS-9991] added logic to execute text extraction for content indexing even if thumbnails are disabled.
